Repository HULKs/hulk, pull requests merged in 2023-04, with the labels that each got.

#167 Add persistence to Twix plots
  tools/twix/src/panels/plot.rs
Labels: tools:Debug Tooling

#183 Resubscribe Parameter Panels in Twix
  tools/twix/src/panels/parameter.rs
Labels: tools:Debug Tooling

#213 Improve SitDown keyframes
  etc/motions/sit_down.json
Labels: cat:Motion

#210 Make Striker glance left and right of ball
  crates/control/src/behavior/dribble.rs
  crates/control/src/motion/head_motion.rs
  crates/control/src/motion/look_at.rs
  crates/types/src/configuration.rs
  crates/types/src/lib.rs
  crates/types/src/motion_command.rs
  etc/configuration/default.json
Labels: cat:Motion, event:GORE23

#221 Tune parameters
  etc/configuration/default.json
Labels: ParameterChangesOnly

#223 Calibrated NAOs.
  etc/configuration/head.P0000074A03S84400010.json
  etc/configuration/head.P0000074A03S84A00011.json
  etc/configuration/head.P0000074A03S85V00012.json
  etc/configuration/head.P0000074A04S8CP00040.json
  etc/configuration/head.P0000074A04S8CP00042.json
  etc/configuration/head.P0000074A05S99M00009.json
  etc/configuration/head.P0000074A06S9A900006.json
  etc/configuration/head.P0000074A06S9A900031.json
Labels: ParameterChangesOnly

#227 Update penalize pose to slightly lean forward
  etc/configuration/default.json
Labels: cat:Motion

#235 Disable robot detection, increase cov matrices
  etc/configuration/default.json
Labels: ParameterChangesOnly

#232 Tune parameters so the robot doesnt hit his head on his shoulder anymore
  etc/configuration/default.json
Labels: ParameterChangesOnly

#236 also allow frames with equal time behind each other
  crates/motionfile/src/timed_spline.rs
Labels: is:Bug

#239 2023 04 27 calibration
  etc/configuration/head.P0000074A03S84400010.json
  etc/configuration/head.P0000074A03S85V00012.json
  etc/configuration/head.P0000074A04S8CP00037.json
  etc/configuration/head.P0000074A04S8CP00040.json
  etc/configuration/head.P0000074A04S8CP00042.json
  etc/configuration/head.P0000074A05S99M00009.json
  etc/configuration/head.P0000074A06S9A900006.json
Labels: ParameterChangesOnly

#241 Calibrated 22
  etc/configuration/head.P0000074A03S84A00011.json
Labels: ParameterChangesOnly

#255 Calibrate some cams
  etc/configuration/head.P0000074A05S99M00009.json
  etc/configuration/head.P0000074A06S9A900031.json
Labels: ParameterChangesOnly

#260 improved stand up motion
  crates/motionfile/src/stabilized_condition.rs
  etc/motions/stand_up_front.json
Labels: cat:Motion

#262 Add parameter to disable the energy saving stand
  crates/control/src/motion/motion_selector.rs
  etc/configuration/default.json
Labels: cat:Motion

#269 Calibrate cams of 28 after repair
  etc/configuration/head.P0000074A04S8CP00056.json
Labels: ParameterChangesOnly

#278 Decay the ball velocity in the ball filter
  crates/control/src/ball_filter.rs
  etc/configuration/default.json
Labels: cat:Filtering, test:Field Needed

#280 calibration 20203-04-29 22, 28, 31, 25
  etc/configuration/head.P0000074A03S84A00011.json
  etc/configuration/head.P0000074A04S8CP00042.json
  etc/configuration/head.P0000074A04S8CP00056.json
Labels: ParameterChangesOnly

#281 Final calibrations 29
  etc/configuration/head.P0000074A05S99M00009.json
  etc/configuration/head.P0000074A06S9A900031.json
Labels: ParameterChangesOnly

#286 Tune image segmentation and line detection
  etc/configuration/default.json
Labels: ParameterChangesOnly

#320 Walking params
  etc/configuration/default.json
Labels: ParameterChangesOnly
