Repository HULKs/hulk, pull requests merged in 2023-10, with the labels that each got.

#573 fix path orientation
  crates/control/src/path_planner.rs
Labels: cat:Behavior

#590 Increase resting ball threshold
  etc/parameters/default.json
Labels: ParameterChangesOnly

#591 delete poses
  etc/poses/AL_Init.pose
  etc/poses/ArmBackStage1.pose
  etc/poses/ArmBackStage2.pose
  etc/poses/Home.pose
  etc/poses/Penalized.pose
  etc/poses/Ready.pose
  etc/poses/Sitting.pose
  etc/poses/TakeAway.pose
  etc/poses/Transport.pose
Labels: is:Cleanup

#596 changed ball search parameters for defender
  crates/control/src/behavior/search.rs
Labels: cat:Motion

#595 remove visible check for kick targets
  crates/control/src/behavior/dribble.rs
  crates/control/src/kick_selector.rs
  crates/types/src/kick_decision.rs
  etc/parameters/default.json
  tools/behavior_simulator/src/cycler.rs
Labels: cat:Behavior

#600 Add documentation for remote compiler vpn routes
  docs/tooling/gnome-settings-vpn-manual.png
  docs/tooling/pepsi.md
Labels: Documentation

#603 Fix image
  docs/tooling/pepsi.md
Labels: Documentation

#604 Fix image (second time)
  docs/tooling/pepsi.md
Labels: Documentation

#610 Remove unused parameter structs
  crates/types/src/parameters.rs
Labels: is:Cleanup

#614 set nao default location to smd
  etc/parameters/nao_location
Labels: ParameterChangesOnly

#619 Recording error handling
  crates/code_generation/src/run.rs
Labels: cat:Framework, cat:Replay
