Repository HULKs/hulk, pull requests merged in 2023-08, with the labels that each got.

#529 Add zstd to requirements for Fedora
  docs/setup/main_setup.md
Labels: Documentation

#416 Implement traits to convert YCbCr422Image to RGB
  crates/types/src/ycbcr422_image.rs
Labels: cat:Vision

#530 Remove unused dependencies
  Cargo.lock
  crates/communication/Cargo.toml
  crates/control/Cargo.toml
  crates/framework/Cargo.toml
  crates/hulk_nao/Cargo.toml
  crates/hulk_webots/Cargo.toml
  crates/motionfile/Cargo.toml
  crates/nao/Cargo.toml
  crates/nao_camera/Cargo.toml
  crates/parameters/Cargo.toml
  crates/serialize_hierarchy/Cargo.toml
  crates/source_analyzer/Cargo.toml
  crates/spl_network_messages/Cargo.toml
  crates/types/Cargo.toml
  crates/vision/Cargo.toml
  tools/aliveness/Cargo.lock
  tools/aliveness/Cargo.toml
  tools/behavior_simulator/Cargo.toml
  tools/fanta/Cargo.toml
  tools/hula/proxy/Cargo.toml
  tools/pepsi/Cargo.toml
  tools/twix/Cargo.toml
Labels: is:Cleanup
