Repository HULKs/hulk, pull requests merged in 2023-09, with the labels that each got.

#520 Cleanup dependencies
  Cargo.lock
  Cargo.toml
  tools/hula/Cargo.toml
Labels: is:Cleanup

#565 Remove legacy locations and add leipzig location
  etc/parameters/field_b/default.json
  etc/parameters/field_c/default.json
  etc/parameters/field_d/default.json
  etc/parameters/field_e/default.json
  etc/parameters/leipzig/default.json
  etc/parameters/louisenlund/default.json
  etc/parameters/nao_location
Labels: ParameterChangesOnly

#567 Check if location is valid
  Cargo.lock
  crates/repository/Cargo.toml
  crates/repository/src/lib.rs
Labels: tools:Tooling
