Repository HULKs/hulk, pull requests merged in 2023-07, with the labels that each got.

#405 tune walking
  etc/configuration/default.json
Labels: ParameterChangesOnly

#407 Graceful error handling for repository parameters
  tools/twix/src/panels/manual_camera_calibration.rs
  tools/twix/src/panels/parameter.rs
  tools/twix/src/repository_parameters.rs
Labels: tools:Debug Tooling

#421 Re-enlist "look at" panel selection in Twix
  tools/twix/src/main.rs
Labels: tools:Debug Tooling

#423 decrease `max_kick_around_obstacle_angle`
  etc/configuration/default.json
Labels: ParameterChangesOnly

#417 Assign optional roles even without game controller
  crates/control/src/role_assignment.rs
Labels: cat:Behavior

#422 Check ball in upper camera
  crates/control/src/ball_filter.rs
Labels: cat:Filtering

#425 Bump webots-rs for R2023b compatibility
  Cargo.lock
  Cargo.toml
Labels: cat:Webots

#426 Include player number seven in the list of viable strikers
  Cargo.lock
  crates/control/src/role_assignment.rs
Labels: cat:Behavior

#434 change fall_protection threshold back to original
  etc/parameters/default.json
Labels: ParameterChangesOnly

#439 Do less high steps
  etc/parameters/default.json
Labels: ParameterChangesOnly

#441 Add empty locations for fields
  etc/parameters/field_a/default.json
  etc/parameters/field_b/default.json
  etc/parameters/field_c/default.json
  etc/parameters/field_d/default.json
  etc/parameters/field_e/default.json
Labels: ParameterChangesOnly

#442 insert 0
  etc/parameters/default.json
Labels: ParameterChangesOnly

#444 Fix duration overflow panics
  crates/control/src/time_to_reach_kick_position.rs
Labels: cat:Behavior, is:EasyWin

#452 Initial extrinsic calibration for 36
  etc/parameters/head.P0000074A09S31C00029.json
Labels: ParameterChangesOnly

#459 Make pepsi location symlink path relative
  crates/repository/src/lib.rs
Labels: tools:Tooling

#461 27, 28, 29, 34, 35, 36, 37 calibrated (extrinsic)
  etc/parameters/head.P0000074A04S8CP00037.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00029.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
Labels: ParameterChangesOnly

#462 32 extrinsic
  etc/parameters/head.P0000074A05S98U00019.json
Labels: ParameterChangesOnly

#473 Walk around offset
  etc/parameters/default.json
Labels: ParameterChangesOnly

#474 change head pitch when falling forwards
  etc/motions/stand_up_front.json
Labels: cat:Motion, ParameterChangesOnly

#476 Tune field E vision parameters
  etc/parameters/field_e/default.json
Labels: ParameterChangesOnly

#494 Increase walk around radius
  etc/parameters/default.json
Labels: ParameterChangesOnly

#496 Basic setup documentation for fedora
  docs/setup/main_setup.md
Labels: Documentation

#437 Move kickoff pose back a little
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/walk_to_kick_off.rs
  etc/parameters/default.json
  tools/behavior_simulator/src/cycler.rs
Labels: cat:Behavior

#490 Change the order of aliveness output
  tools/pepsi/src/aliveness.rs
Labels: tools:Tooling

#500 23 calibration extrinsic
  etc/parameters/head.P0000074A03S85B00016.json
Labels: ParameterChangesOnly

#497 Make some corrections for Fedora setup docs
  docs/setup/main_setup.md
Labels: Documentation

#515 Document registry certificate for v3 CI
  tools/ci/github-runners/v3/README.md
Labels: ParameterChangesOnly

#525 Tune walking for lab
  etc/parameters/body.P0000073A03S83I00015.json
  etc/parameters/body.P0000073A03S84A00012.json
  etc/parameters/body.P0000073A03S85B00002.json
  etc/parameters/body.P0000073A06S8CP00035.json
  etc/parameters/body.P0000073A06S8CP00038.json
  etc/parameters/body.P0000073A06S8CP00043.json
  etc/parameters/body.P0000073A06S8CP00054.json
  etc/parameters/body.P0000073A10S98U00008.json
  etc/parameters/body.P0000073A10S99M00002.json
  etc/parameters/body.P0000073A10S9A900008.json
  etc/parameters/body.P0000073A10S9A900011.json
  etc/parameters/default.json
Labels: cat:Walking, ParameterChangesOnly
