Repository HULKs/hulk, pull requests merged in 2023-06, with the labels that each got.

#354 use correct kick when checking for obstacles
  crates/control/src/kick_selector.rs
Labels: is:Bug

#362 Gammaray follow symlinks
  crates/nao/src/lib.rs
Labels: tools:Tooling

#364 Allow to correct camera matrices
  crates/control/src/camera_matrix_calculator.rs
  crates/serialize_hierarchy/src/not_supported.rs
  crates/types/src/camera_matrix.rs
  crates/types/src/horizon.rs
Labels: calibration:Automatic

#363 Add Webots keyboard shortcuts for head buttons
  crates/hulk/src/webots/keyboard_device.rs
Labels: calibration:Automatic

#357 Reduce max allowed adjustment velocity of walk step adjustment
  etc/configuration/default.json
Labels: cat:Motion, cat:Walking

#365 Drop all obstacle hypotheses when unpenalized (without PrimaryStateTransition)
  crates/control/src/obstacle_filter.rs
Labels: cat:Filtering

#371 Fix X legs on 31
  etc/configuration/head.P0000074A06S9A900006.json
Labels: ParameterChangesOnly

#359 check for shootout when lookaround
  crates/control/src/behavior/look_around.rs
Labels: cat:Behavior

#380 Twix Panel IDs
  tools/twix/src/main.rs
Labels: tools:Debug Tooling

#382 Fix building with "dev" profile
  crates/repository/src/lib.rs
Labels: tools:Tooling

#397 improve sidesteps, improve turns
  etc/configuration/default.json
Labels: cat:Walking, ParameterChangesOnly

#401 Falling threshold 2
  etc/configuration/default.json
Labels: ParameterChangesOnly
