Repository HULKs/hulk, pull requests merged in 2024-12, with the labels that each got.

#1511 Mujoco Env
  Cargo.lock
  tools/machine-learning/mujoco/.gitignore
  tools/machine-learning/mujoco/README.md
  tools/machine-learning/mujoco/interactive_viewer.py
  tools/machine-learning/mujoco/nao_env/__init__.py
  tools/machine-learning/mujoco/nao_env/nao_standup.py
  tools/machine-learning/mujoco/pyproject.toml
  tools/machine-learning/mujoco/standup.py
  tools/machine-learning/mujoco/uv.lock
Labels: cat:MachineLearning

#1529 beautify overview page & image
  docs/framework/communication.md
  docs/framework/communication_dataflow.png
  docs/framework/database_dataflow.png
  docs/framework/dataflow.png
  docs/framework/node-dark.png
  docs/framework/node-light.png
  docs/framework/nodes.md
  docs/framework/overview-dark.png
  docs/framework/overview-light.png
  docs/framework/overview.drawio
  docs/framework/overview.drawio.png
  docs/framework/overview.md
  docs/framework/runtime.md
Labels: Documentation

#1478 Twix CompletionEdit
  Cargo.lock
  Cargo.toml
  crates/hulk_replayer/src/labels.rs
  crates/hulk_replayer/src/timeline.rs
  crates/hulk_widgets/Cargo.toml
  crates/hulk_widgets/src/completion_edit.rs
  crates/hulk_widgets/src/lib.rs
  crates/hulk_widgets/src/nao_path_completion_edit.rs
  crates/hulk_widgets/src/segmented_control.rs
  tools/annotato/src/widgets/class_selector.rs
  tools/twix/Cargo.toml
  tools/twix/config_default.toml
  tools/twix/src/configuration.rs
  tools/twix/src/configuration/keybind_plugin.rs
  tools/twix/src/configuration/merge.rs
  tools/twix/src/main.rs
  tools/twix/src/panels/behavior_simulator.rs
  tools/twix/src/panels/enum_plot.rs
  tools/twix/src/panels/image_color_select.rs
  tools/twix/src/panels/map/mod.rs
  tools/twix/src/panels/parameter.rs
  tools/twix/src/panels/plot.rs
  tools/twix/src/panels/text.rs
  tools/twix/src/reachable_naos.rs
  tools/twix/src/selectable_panel_macro.rs
  tools/widget_gallery/Cargo.toml
  tools/widget_gallery/src/main.rs
Labels: tools:Debug Tooling, is:Bugfix

#1530 vendored lua
  Cargo.lock
  Cargo.toml
Labels: tools:Debug Tooling

#1534 Refactor: merge config as TOML value
  tools/twix/src/configuration.rs
  tools/twix/src/configuration/keys.rs
  tools/twix/src/configuration/merge.rs
Labels: is:Refactoring

#1506 Extend imagine
  Cargo.lock
  Cargo.toml
  crates/code_generation/src/execution.rs
  crates/framework/src/recording_index.rs
  crates/hulk_imagine/Cargo.toml
  crates/hulk_imagine/build.rs
  crates/hulk_imagine/src/extractor_hardware_interface.rs
  crates/hulk_imagine/src/main.rs
  crates/hulk_imagine/src/mcap_converter.rs
  crates/hulk_imagine/src/serializer.rs
  crates/hulk_imagine/src/write_to_mcap.rs
  crates/path_serde_derive/src/introspect.rs
Labels: cat:Replay

#1523 Sidekicks in ball model
  crates/control/src/ball_filter.rs
  crates/control/src/motion/walking_engine.rs
  crates/walking_engine/src/mode.rs
Labels: cat:Filtering

#1536 Add taplo to CI image
  tools/ci/github-runners/Containerfile
Labels: tools:CI

#1525 Tune kick and walk parameters
  etc/parameters/default.json
Labels: cat:Walking, ParameterChangesOnly

#1542 rename joints
  tools/machine-learning/mujoco/model/nao.xml
Labels: cat:MuJoCo

#1540 Fix CI (hopefully)
  .github/workflows/ci-image.yml
  tools/ci/github-runners/Containerfile
Labels: tools:CI
