Repository HULKs/hulk, pull requests merged in 2024-09, with the labels that each got.

#1433 update image, add Ball Candidates view, beautify
  docs/robotics/perception/ball_candidates.jpg
  docs/robotics/perception/raw_ball_candidates.jpg
  docs/robotics/perception/vision.md
Labels: Documentation

#1432 Twix Lüfter abschalten (mal wieder)
  crates/communication/src/client.rs
Labels: tools:Debug Tooling, is:Bugfix

#1434 Update docs feet detection / update feet detection view in twix
  Cargo.lock
  docs/robotics/perception/feet_detection_image_view.jpg
  docs/robotics/perception/feet_detection_map_view.jpg
  docs/robotics/perception/vision.md
  tools/twix/Cargo.toml
  tools/twix/src/panels/image/overlays/feet_detection.rs
Labels: Documentation, tools:Debug Tooling

#1436 General Documentation for Behavior and Motion
  docs/robotics/behavior/behavior.md
  docs/robotics/behavior/overview.md
  docs/robotics/motion/overview.md
  docs/robotics/overview.md
  mkdocs.yml
Labels: Documentation

#1437 Use real tm symbol
  docs/setup/development_environment.md
Labels: Documentation

#1440 Twix documentation
  docs/setup/development_environment.md
  docs/tooling/twix.md
Labels: Documentation

#1442 Update docs workflow
  docs/setup/configure_team.md
  docs/setup/development_environment.md
  docs/setup/upload.md
  docs/workflow/competition.md
  docs/workflow/development.md
  docs/workflow/getting_started.md
  docs/workflow/overview.md
  mkdocs.yml
Labels: Documentation

#1444 Update docs vision
  docs/robotics/perception/ball_candidates.jpg
  docs/robotics/perception/field_border.jpg
  docs/robotics/perception/image_segments_border_dark.jpg
  docs/robotics/perception/image_segments_border_light.jpg
  docs/robotics/perception/image_segments_limbs_dark.jpg
  docs/robotics/perception/image_segments_limbs_light.jpg
  docs/robotics/perception/line_detection.jpg
  docs/robotics/perception/raw_ball_candidates.jpg
  docs/robotics/perception/raw_ball_candidates_dark.jpg
  docs/robotics/perception/raw_ball_candidates_light.jpg
  docs/robotics/perception/segmented_image.jpg
  docs/robotics/perception/vision.md
Labels: Documentation

#1443 Beautify development process
  docs/workflow/development.md
  mkdocs.yml
Labels: Documentation

#1438 Add link to workflow, add linux distro info
  docs/setup/development_environment.md
  docs/setup/how_to_choose_os.jpg
  docs/setup/overview.md
Labels: Documentation

#1445 Update docs audio
  docs/robotics/perception/audio.md
  docs/workflow/competition.md
Labels: Documentation
