Repository HULKs/hulk, pull requests merged in 2024-02, with the labels that each got.

#716 Renaming module to node
  docs/framework/node.drawio
  docs/framework/node.drawio.png
Labels: Documentation

#722 Fix setting internal state in game controller state filter
  crates/control/src/game_controller_state_filter.rs
Labels: cat:Filtering

#726 Remove dbg print
  crates/control/src/rule_obstacle_composer.rs
Labels: is:Cleanup

#729 Distant rainbows
  scripts/remoteWorkspace
Labels: tools:Tooling, is:EasyWin

#730 Make the CI green again
  .github/workflows/pull-request.yml
Labels: tools:CI
