Repository HULKs/hulk, pull requests merged in 2024-07, with the labels that each got.

#1090 Revert "Image zZoom für Alex (#1023)"
  Cargo.lock
  crates/coordinate_systems/src/lib.rs
  tools/twix/Cargo.toml
  tools/twix/src/main.rs
  tools/twix/src/panels/image/mod.rs
  tools/twix/src/panels/image_color_select.rs
  tools/twix/src/panels/image_segments.rs
  tools/twix/src/panels/map/mod.rs
  tools/twix/src/twix_painter.rs
  tools/twix/src/zoom_and_pan.rs
Labels: is:Bug, RC24

#1087 Look at all previous players to decide if replacement keeper is best role
  crates/control/src/role_assignment.rs
  crates/spl_network_messages/src/lib.rs
  tests/behavior/two_replacementkeepers.lua
Labels: cat:Behavior, RC24

#1086 Sacrificial nao
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/lib.rs
  crates/control/src/referee_pose_detection_filter.rs
  crates/control/src/sacrificial_lamb.rs
  crates/hulk_behavior_simulator/src/fake_data.rs
  crates/hulk_manifest/src/lib.rs
  crates/types/src/pose_detection.rs
  etc/parameters/default.json
Labels: RC24

#1019 Catching steps by way of ZMP
  Cargo.lock
  crates/control/src/motion/walking_engine.rs
  crates/control/src/zero_moment_point_provider.rs
  crates/geometry/Cargo.toml
  crates/geometry/src/convex_hull.rs
  crates/geometry/src/is_inside_polygon.rs
  crates/geometry/src/lib.rs
  crates/vision/src/limb_projector.rs
  crates/walking_engine/src/lib.rs
  crates/walking_engine/src/mode/catching.rs
  crates/walking_engine/src/mode/walking.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Walking, RC24

#1044 Refactor Ball Filter
  Cargo.lock
  Cargo.toml
  crates/ball_filter/Cargo.toml
  crates/ball_filter/src/ball_position.rs
  crates/ball_filter/src/hypothesis.rs
  crates/ball_filter/src/hypothesis/moving.rs
  crates/ball_filter/src/hypothesis/resting.rs
  crates/ball_filter/src/lib.rs
  crates/control/Cargo.toml
  crates/control/src/ball_filter.rs
  crates/control/src/ball_state_composer.rs
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/penalty_shot_direction_estimation.rs
  crates/control/src/role_assignment.rs
  crates/control/src/search_suggestor.rs
  crates/hulk/Cargo.toml
  crates/hulk_behavior_simulator/Cargo.toml
  crates/hulk_behavior_simulator/src/fake_data.rs
  crates/hulk_behavior_simulator/src/state.rs
  crates/hulk_imagine/Cargo.toml
  crates/hulk_nao/Cargo.toml
  crates/hulk_replayer/Cargo.toml
  crates/hulk_webots/Cargo.toml
  crates/types/src/ball_filter.rs
  crates/types/src/ball_position.rs
  crates/types/src/lib.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
  tools/twix/Cargo.toml
  tools/twix/src/panels/map/layers/ball_position.rs
  tools/twix/src/panels/map/layers/mod.rs
Labels: cat:Filtering, RC24

#1100 Reapply: Image zoom
  Cargo.lock
  crates/coordinate_systems/src/lib.rs
  tools/twix/Cargo.toml
  tools/twix/src/main.rs
  tools/twix/src/panels/image/mod.rs
  tools/twix/src/panels/image_color_select.rs
  tools/twix/src/panels/image_segments.rs
  tools/twix/src/panels/map/mod.rs
  tools/twix/src/twix_painter.rs
  tools/twix/src/zoom_and_pan.rs
Labels: tools:Debug Tooling

#1101 kickoff position with rotation
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/walk_to_kick_off.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Behavior, RC24

#1078 Use hsv color space
  crates/types/src/color.rs
  crates/types/src/field_color.rs
  crates/vision/src/field_color_detection.rs
  etc/parameters/default.json
  tools/twix/src/panels/image_segments.rs
  tools/twix/src/panels/vision_tuner.rs
Labels: cat:Vision, tools:Debug Tooling, tools:Tooling, RC24

#1105 Fix test cases
  crates/vision/src/image_segmenter.rs
Labels: RC24

#1108 Avoid singularity in testcase
  crates/control/src/behavior/walk_to_pose.rs
Labels: is:Bugfix

#1088 Penalty shootout keeper improvements
  crates/control/src/active_vision.rs
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/localization.rs
  crates/control/src/penalty_shot_direction_estimation.rs
Labels: RC24

#1093 Move pose detection toggle
  crates/control/src/behavior/initial.rs
  crates/control/src/behavior/node.rs
  crates/object_detection/src/pose_detection.rs
Labels: RC24

#1106 Add `.roll`,`.pitch`,`.yaw` to UnitQuaternion
  crates/path_serde/src/implementation.rs
  crates/path_serde/src/not_supported.rs
Labels: RC24

#1006 Central gamestate timeing
  crates/control/src/filtered_game_controller_state_timer.rs
  crates/control/src/lib.rs
  crates/hulk_behavior_simulator/build.rs
  crates/hulk_manifest/src/lib.rs
  crates/spl_network_messages/src/game_controller_state_message.rs
  crates/types/src/cycle_time.rs
  crates/types/src/filtered_game_controller_state.rs
  crates/types/src/last_filtered_game_controller_state_change.rs
  crates/types/src/lib.rs
  crates/types/src/players.rs
Labels: RC24

#1110 Make URLs in docs hyperlinks
  crates/control/src/a_star.rs
  crates/geometry/src/line_segment.rs
Labels: Documentation

#1111 Higher ball candidates
  crates/vision/src/perspective_grid_candidates_provider.rs
Labels: cat:Vision, RC24, is:Bugfix

#1076 Center circle calibration (solver)
  crates/calibration/src/center_circle/circle_points.rs
  crates/calibration/src/center_circle/measurement.rs
  crates/calibration/src/center_circle/mod.rs
  crates/calibration/src/center_circle/residuals.rs
  crates/calibration/src/corrections.rs
  crates/calibration/src/goal_box/lines.rs
  crates/calibration/src/goal_box/measurement.rs
  crates/calibration/src/goal_box/mod.rs
  crates/calibration/src/goal_box/residuals.rs
  crates/calibration/src/jacobian.rs
  crates/calibration/src/lib.rs
  crates/calibration/src/problem.rs
  crates/calibration/src/residuals.rs
  crates/control/src/calibration_controller.rs
  crates/vision/src/calibration_measurement_provider.rs
Labels: calibration:Automatic, RC24

#1097 Enable visual referee recording
  etc/parameters/default.json
Labels: RC24

#1117 print full backtrace if available
  crates/code_generation/src/execution.rs
Labels: RC24

#1120 tune field color for SMD
  etc/parameters/default.json
Labels: ParameterChangesOnly, RC24

#923 Fix tracking lost ground contact
  crates/control/src/localization.rs
Labels: cat:Localization, GO24, RC24

#1121 bump os version
  Cargo.lock
  crates/constants/src/lib.rs
  tools/pepsi/Cargo.toml
Labels: RC24

#1116 Add paths to nalgebra types
  Cargo.lock
  crates/path_serde/Cargo.toml
  crates/path_serde/src/implementation.rs
  crates/path_serde/src/not_supported.rs
Labels: RC24

#1118 Keeper WideStance
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/node.rs
  crates/control/src/motion/dispatching_interpolator.rs
  crates/control/src/motion/mod.rs
  crates/control/src/motion/motion_selector.rs
  crates/control/src/motion/motor_commands_collector.rs
  crates/control/src/motion/wide_stance.rs
  crates/hulk_manifest/src/lib.rs
  crates/types/src/action.rs
  crates/types/src/motion_command.rs
  crates/types/src/motion_selection.rs
  crates/types/src/parameters.rs
  etc/motions/wide_stance.json
  etc/parameters/default.json
Labels: cat:Motion, RC24

#1126 Use correct clock for foot bumper filter
  crates/control/src/foot_bumper_filter.rs
Labels: is:Bugfix

#1123 default opponent goalkeeper number when above 7
  crates/spl_network_messages/src/game_controller_state_message.rs
Labels: RC24, is:Bugfix

#1124 save all opponent penalties
  crates/spl_network_messages/src/game_controller_state_message.rs
Labels: RC24, is:Bugfix

#1113 Separate Messages
  crates/control/src/referee_pose_detection_filter.rs
  crates/control/src/role_assignment.rs
  crates/control/src/visual_referee_filter.rs
  crates/spl_network/src/message_filter.rs
  crates/spl_network_messages/src/lib.rs
  crates/spl_network_messages/src/visual_referee_message.rs
  crates/types/src/messages.rs
Labels: RC24

#1129 Remove RequiredInput - CameraMatrices
  crates/control/src/ball_filter.rs
Labels: cat:Filtering, RC24, is:Bugfix

#1132 Remove Hypotheses if no ground contact
  crates/ball_filter/src/lib.rs
  crates/control/src/ball_filter.rs
Labels: cat:Filtering, RC24, is:Bugfix

#1107 Use ahrs Madgwick for orientation
  Cargo.lock
  crates/control/src/ball_filter.rs
  crates/control/src/fall_state_estimation.rs
  crates/control/src/ground_provider.rs
  crates/control/src/motion/walking_engine.rs
  crates/control/src/obstacle_filter.rs
  crates/control/src/odometry.rs
  crates/control/src/orientation_filter.rs
  crates/filtering/Cargo.toml
  crates/filtering/src/lib.rs
  crates/filtering/src/madgwick.rs
  crates/filtering/src/orientation_filtering.rs
  crates/types/src/lib.rs
  crates/types/src/orientation_filter.rs
  crates/walking_engine/src/foot_leveling.rs
  crates/walking_engine/src/lib.rs
  crates/walking_engine/src/step_state.rs
  etc/parameters/default.json
Labels: RC24

#1128 Remove Visual Referee Challenge message
  crates/control/src/lib.rs
  crates/control/src/visual_referee_filter.rs
  crates/hulk_manifest/src/lib.rs
  crates/spl_network/src/endpoint.rs
  crates/spl_network_messages/src/lib.rs
  crates/spl_network_messages/src/visual_referee_message.rs
  crates/types/src/messages.rs
Labels: is:Cleanup, RC24

#1134 Use Correct Time for Prediction
  crates/control/src/ball_filter.rs
Labels: cat:Filtering, RC24, is:Bugfix

#1112 Fix Sacrificial Nao
  crates/control/src/sacrificial_lamb.rs
Labels: RC24

#1094 Better pose filtering by confidences
  Cargo.lock
  crates/control/src/behavior/node.rs
  crates/control/src/referee_pose_detection_filter.rs
  crates/hulk_manifest/src/lib.rs
  crates/object_detection/src/lib.rs
  crates/object_detection/src/pose_detection.rs
  crates/object_detection/src/pose_filter.rs
  crates/object_detection/src/pose_interpretation.rs
  crates/types/src/bounding_box.rs
  crates/types/src/pose_detection.rs
  crates/types/src/pose_kinds.rs
  etc/parameters/default.json
  tools/twix/Cargo.toml
  tools/twix/src/panels/image/overlay.rs
  tools/twix/src/panels/image/overlays/pose_detection.rs
  tools/twix/src/panels/map/layers/pose_detection.rs
  tools/twix/src/panels/map/layers/referee_position.rs
Labels: RC24

#1135 Flush Control Frames to LoLA
  tools/hula/Cargo.lock
  tools/hula/proxy/Cargo.toml
  tools/hula/proxy/src/proxy.rs
Labels: RC24

#1049 Animation Mode
  crates/control/src/behavior/animation.rs
  crates/control/src/behavior/mod.rs
  crates/control/src/behavior/node.rs
  crates/control/src/button_filter.rs
  crates/control/src/led_status.rs
  crates/control/src/motion/animation.rs
  crates/control/src/motion/dispatching_interpolator.rs
  crates/control/src/motion/head_motion.rs
  crates/control/src/motion/mod.rs
  crates/control/src/motion/motion_selector.rs
  crates/control/src/motion/motor_commands_collector.rs
  crates/control/src/primary_state_filter.rs
  crates/filtering/src/debounce_button.rs
  crates/filtering/src/lib.rs
  crates/filtering/src/tap_detector.rs
  crates/hulk_behavior_simulator/src/state.rs
  crates/hulk_manifest/src/lib.rs
  crates/types/src/action.rs
  crates/types/src/buttons.rs
  crates/types/src/color.rs
  crates/types/src/motion_command.rs
  crates/types/src/motion_selection.rs
  crates/types/src/primary_state.rs
  etc/parameters/default.json
Labels: cat:Behavior, cat:Motion, RC24

#1136 Warn if cycle takes too long
  crates/code_generation/src/cyclers.rs
  crates/hulk_behavior_simulator/src/interfake.rs
  crates/hulk_behavior_simulator/src/lib.rs
Labels: cat:Audio, tools:Debug Tooling, RC24

#1147 45 degree Kick-Off-Striker
  etc/parameters/default.json
Labels: ParameterChangesOnly, RC24

#1045 Camera Error Projection
  crates/ball_filter/src/hypothesis.rs
  crates/ball_filter/src/hypothesis/moving.rs
  crates/ball_filter/src/hypothesis/resting.rs
  crates/ball_filter/src/lib.rs
  crates/control/src/ball_filter.rs
  crates/control/src/led_status.rs
  crates/projection/src/camera_projection.rs
  crates/projection/src/lib.rs
  crates/types/src/ball.rs
  crates/types/src/multivariate_normal_distribution.rs
  crates/types/src/parameters.rs
  crates/vision/src/ball_detection.rs
  crates/vision/src/feet_detection.rs
  etc/parameters/default.json
  tools/twix/src/panels/image/overlays/ball_detection.rs
  tools/twix/src/panels/map/layers/ball_filter.rs
  tools/twix/src/panels/map/layers/ball_measurements.rs
  tools/twix/src/panels/map/layers/ball_position.rs
  tools/twix/src/panels/map/layers/mod.rs
  tools/twix/src/panels/map/mod.rs
  tools/twix/src/twix_painter.rs
Labels: cat:Filtering, RC24

#1148 Print warning when cycle takes too long
  Cargo.lock
  crates/code_generation/src/cyclers.rs
  crates/hulk/Cargo.toml
Labels: tools:Debug Tooling

#1146 Rename twix config toml
  tools/twix/config_default.toml
  tools/twix/src/configuration.rs
Labels: tools:Debug Tooling, RC24

#1141 Upgrade image to 7.5.3 (HuLA upgrade)
  Cargo.lock
  crates/constants/src/lib.rs
  tools/pepsi/Cargo.toml
Labels: RC24

#1142 Slightly reduce step size
  etc/parameters/default.json
Labels: ParameterChangesOnly, RC24

#1150 Walk Slow/Normal/Fast
  crates/control/src/behavior/dribble.rs
  crates/control/src/behavior/intercept_ball.rs
  crates/control/src/behavior/lost_ball.rs
  crates/control/src/behavior/search.rs
  crates/control/src/behavior/walk_to_pose.rs
  crates/control/src/motion/step_planner.rs
  crates/types/src/motion_command.rs
  etc/parameters/default.json
Labels: RC24

#1104 Add dependencies
  docs/setup/development_environment.md
Labels: Documentation, RC24

#1154 look at rule ball or penalty spot during set of penalty kicks
  crates/control/src/ball_state_composer.rs
  crates/control/src/behavior/stand.rs
  tests/behavior/penalty_shootout.lua
Labels: RC24, is:Bugfix

#1144 fix kick off kick targets
  crates/control/src/kick_target_provider.rs
Labels: RC24

#1159 add toggle between old calibration mode and new calibration mode
  crates/control/src/behavior/calibrate.rs
  crates/control/src/behavior/node.rs
  etc/parameters/default.json
Labels: calibration:Manual, RC24

#1158 Set VPN routes on naos
  Cargo.lock
  crates/constants/src/lib.rs
  tools/pepsi/Cargo.toml
Labels: RC24

#1067 Image color select 2: Malen für Zahlen
  Cargo.lock
  crates/types/src/field_color.rs
  tools/twix/Cargo.toml
  tools/twix/src/panels/image_color_select.rs
Labels: cat:Vision, tools:Tooling, RC24

#1160 Historical Revisionism
  crates/code_generation/src/cyclers.rs
  crates/control/src/game_controller_filter.rs
  crates/hulk_replayer/src/main.rs
  crates/vision/src/image_receiver.rs
Labels: cat:Replay, RC24, is:Bugfix

#1163 arms_up_squat faster and stabelised it
  etc/motions/arms_up_squat.json
Labels: cat:Motion, RC24

#1161 Penalty keeper CenterJump
  crates/control/src/behavior/jump.rs
  crates/control/src/motion/center_jump.rs
  crates/control/src/motion/dispatching_interpolator.rs
  crates/control/src/motion/mod.rs
  crates/control/src/motion/motion_selector.rs
  crates/control/src/motion/motor_commands_collector.rs
  crates/control/src/penalty_shot_direction_estimation.rs
  crates/hulk_manifest/src/lib.rs
  crates/types/src/motion_command.rs
  crates/types/src/motion_selection.rs
  crates/types/src/parameters.rs
  crates/types/src/penalty_shot_direction.rs
  etc/motions/center_jump.json
  etc/parameters/default.json
Labels: cat:Motion, RC24

#1167 arms up for goalkeeper during set for penalty kicks
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/stand.rs
  crates/control/src/motion/arms_up_stand.rs
  crates/control/src/motion/dispatching_interpolator.rs
  crates/control/src/motion/mod.rs
  crates/control/src/motion/motion_selector.rs
  crates/control/src/motion/motor_commands_collector.rs
  crates/hulk_manifest/src/lib.rs
  crates/types/src/motion_command.rs
  crates/types/src/motion_selection.rs
  etc/motions/arms_up_squat.json
  etc/motions/arms_up_stand.json
  etc/motions/center_jump.json
Labels: cat:Motion, RC24

#1168 Disbale obstacles in penalty shootout
  crates/control/src/kick_target_provider.rs
Labels: RC24

#1171 relax penalized pose by spacing arms a little bit further away from body
  etc/parameters/default.json
Labels: ParameterChangesOnly, RC24

#1174 Update the documentation overview
  docs/index.md
Labels: Documentation, RC24

#1175 Use workspace fields for all crates
  crates/argument_parsers/Cargo.toml
  crates/coordinate_systems/Cargo.toml
  crates/hulk_behavior_simulator/Cargo.toml
  crates/linear_algebra/Cargo.toml
  crates/object_detection/Cargo.toml
  crates/parameter_tester/Cargo.toml
  tools/annotato/Cargo.toml
  tools/hula/Cargo.toml
  tools/hula/proxy/Cargo.toml
  tools/hula/types/Cargo.toml
Labels: is:Cleanup, RC24

#1176 Add parameters for walk speed of actions
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/dribble.rs
  crates/control/src/behavior/intercept_ball.rs
  crates/control/src/behavior/lost_ball.rs
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/search.rs
  crates/control/src/behavior/support.rs
  crates/control/src/behavior/walk_to_kick_off.rs
  crates/control/src/behavior/walk_to_penalty_kick.rs
  crates/control/src/behavior/walk_to_pose.rs
  crates/types/src/motion_command.rs
  etc/parameters/default.json
Labels: cat:Behavior, is:Easy, RC24

#1178 Charging box files and documentation
  docs/charging_box/building_your_own.md
  docs/charging_box/overview.md
  tools/charging-box/.gitattributes
  tools/charging-box/.gitignore
  tools/charging-box/README.md
  tools/charging-box/cad/charging-box.f3z
  tools/charging-box/cad/exports/AC-DC-cover-holder.stl
  tools/charging-box/cad/exports/AC-cover-holder.stl
  tools/charging-box/cad/exports/AC-cover.dxf
  tools/charging-box/cad/exports/DC-cover-handle.stl
  tools/charging-box/cad/exports/DC-cover-holder.stl
  tools/charging-box/cad/exports/DC-cover.dxf
  tools/charging-box/cad/exports/fan-cover.stl
  tools/charging-box/cad/exports/fan-holder.stl
  tools/charging-box/cad/exports/rain-cover-hulks.stl
  tools/charging-box/cad/exports/rain-cover.stl
  tools/charging-box/cad/exports/side-plate-1.stl
  tools/charging-box/cad/exports/side-plate-2.stl
  tools/charging-box/cad/exports/spacer.amf
  tools/charging-box/cad/spacer.scad
  tools/charging-box/pcb/Library.pretty/TerminalBlock_bornier-8_P5.08mm.kicad_mod
  tools/charging-box/pcb/Library.pretty/XL4015-CC-CV-Module.kicad_mod
  tools/charging-box/pcb/charging-box-gerbers.zip
  tools/charging-box/pcb/charging-box.kicad_pcb
  tools/charging-box/pcb/charging-box.kicad_pro
  tools/charging-box/pcb/charging-box.kicad_sch
  tools/charging-box/pcb/fp-lib-table
Labels: RC24, tools:hardware

#1180 Fix and improve charging box documentation
  docs/charging_box/building_your_own.md
  docs/tooling/charging_box/building_your_own.md
  docs/tooling/charging_box/overview.md
  mkdocs.yml
  tools/charging-box/README.md
Labels: RC24, tools:hardware

#1187 Add robocup 24 field locations
  etc/parameters/nao_location
  etc/parameters/rc24a/default.json
  etc/parameters/rc24b/default.json
  etc/parameters/rc24c/default.json
  etc/parameters/rc24d/default.json
  etc/parameters/rc24e/default.json
Labels: ParameterChangesOnly, RC24

#1188 Tune Vision, die Erste
  etc/parameters/rc24a/default.json
  etc/parameters/rc24b/default.json
  etc/parameters/rc24c/default.json
  etc/parameters/rc24d/default.json
  etc/parameters/rc24e/default.json
Labels: ParameterChangesOnly

#1191 Tune walking
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1194 (parameters) move striker back
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1193 camera calibration 23, 32, 37, 40
  etc/parameters/head.P0000074A03S85B00016.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
Labels: ParameterChangesOnly, calibration:Manual, RC24

#1182 Kick-Decision anticipation
  crates/control/src/behavior/dribble.rs
  crates/control/src/kick_selector.rs
  crates/control/src/motion/step_planner.rs
  crates/control/src/motion/walking_engine.rs
  crates/control/src/obstacle_filter.rs
  crates/control/src/world_state_composer.rs
  crates/coordinate_systems/src/lib.rs
  crates/types/src/world_state.rs
  tools/twix/src/panels/map/layers/kick_decisions.rs
Labels: RC24

#1181 fix kick variant enabling
  crates/control/src/kick_selector.rs
  crates/control/src/kick_target_provider.rs
Labels: RC24

#1192 Deaf ref
  crates/object_detection/src/pose_filter.rs
  crates/types/src/pose_detection.rs
  etc/parameters/default.json
  tools/twix/src/panels/image/overlays/pose_detection.rs
Labels: RC24

#1207 Ball Filter - Throw out by validity
  crates/control/src/ball_filter.rs
Labels: cat:Filtering, RC24, is:Bugfix

#1228 Fix referee position overlay
  tools/twix/src/panels/map/layers/referee_position.rs
Labels: is:Bug, RC24

#1210 Fix head joint stiffness
  crates/control/src/motion/motor_commands_collector.rs
Labels: cat:Motion, is:Bugfix

#1172 add additional hysteresis_from_thresholds
  crates/control/src/ball_state_composer.rs
  crates/control/src/behavior/walk_to_pose.rs
  crates/energy_optimization/src/current_minimizer.rs
  crates/energy_optimization/src/parameters.rs
  crates/filtering/src/hysteresis.rs
  etc/parameters/default.json
Labels: RC24

#1231 remove accidental parameters object wrap
  etc/parameters/head.P0000074A03S85B00016.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly

#1198 Add --prepare flag for pepsi upload and pregame
  Cargo.lock
  tools/pepsi/Cargo.toml
  tools/pepsi/src/pre_game.rs
  tools/pepsi/src/upload.rs
Labels: tools:Tooling, RC24

#1232 Reduce visual referee threshold
  etc/parameters/default.json
Labels: ParameterChangesOnly, RC24

#1229 Fix saving camera matrix
  crates/parameters/src/directory.rs
  tools/twix/src/panels/manual_camera_calibration.rs
Labels: calibration:Manual, is:Bugfix

#1202 Fix uninitialized cycler databases
  crates/code_generation/src/cyclers.rs
Labels: cat:Framework, is:Bug, RC24

#1235 Bump image and pepsi version
  Cargo.lock
  crates/constants/src/lib.rs
  tools/pepsi/Cargo.toml
Labels: tools:SDK, tools:Tooling, is:Easy, RC24

#1204 only Forward kicks as penalty kicks
  crates/control/src/kick_target_provider.rs
  etc/parameters/default.json
Labels: RC24

#1179 Sample more pixels for color calculation of segments
  crates/types/src/ycbcr422_image.rs
  crates/vision/src/image_segmenter.rs
  tools/twix/src/panels/image_color_select.rs
Labels: cat:Vision

#1239 Fix Twix Map Ground View
  tools/twix/src/panels/map/mod.rs
Labels: tools:Debug Tooling, is:Bugfix

#1237 Reduce liquidity
  Cargo.lock
  Cargo.toml
  crates/code_generation/src/execution.rs
  crates/hulk_behavior_simulator/src/robot.rs
  crates/hulk_behavior_simulator/src/server.rs
  crates/hulk_behavior_simulator/src/simulator.rs
  crates/parameter_tester/src/main.rs
  crates/parameters/Cargo.toml
  crates/parameters/src/directory.rs
  etc/parameters/default.json
  etc/parameters/rc24a/default.json
  etc/parameters/rc24b/default.json
  etc/parameters/rc24c/default.json
  etc/parameters/rc24d/default.json
  etc/parameters/rc24e/default.json
Labels: ParameterChangesOnly

#1240 Tune Kick Decisions
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1173 Tune energy optimization
  crates/filtering/src/hysteresis.rs
  etc/parameters/default.json
Labels: ParameterChangesOnly, RC24

#1244 Use correct `Side` type
  crates/control/src/ball_state_composer.rs
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/support.rs
  crates/types/src/field_dimensions.rs
  crates/types/src/world_state.rs
Labels: is:Bug, RC24

#1242 Slightly liquify again
  crates/code_generation/src/execution.rs
Labels: is:Bugfix

#1247 Better defender corner kick positioning
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/node.rs
  crates/types/src/action.rs
  tests/behavior/corner_kicks.lua
Labels: cat:Behavior, RC24

#1200 limit midfielders to exist in smarter offensive supporting positions
  crates/control/src/behavior/support.rs
  etc/parameters/default.json
Labels: cat:Behavior

#1233 Cameracalibration 39 34
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
Labels: ParameterChangesOnly, calibration:Manual

#1250 Move targets into goal
  crates/control/src/kick_target_provider.rs
Labels: cat:Motion

#1251 Fix shuffeling
  etc/parameters/body.P0000073A19S31T00003.json
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1246 Factor out distance_to_* methods to own trait
  crates/calibration/src/goal_box/residuals.rs
  crates/control/src/behavior/intercept_ball.rs
  crates/geometry/src/circle.rs
  crates/geometry/src/lib.rs
  crates/geometry/src/line.rs
  crates/geometry/src/line_segment.rs
  crates/ransac/src/lib.rs
  crates/vision/src/line_detection.rs
Labels: is:Refactoring

#1254 Enforcing difference between Line and LineSegment and clean up related code
  crates/calibration/src/goal_box/lines.rs
  crates/control/src/camera_matrix_calculator.rs
  crates/control/src/localization.rs
  crates/geometry/src/line.rs
  crates/geometry/src/line_segment.rs
  crates/types/src/field_border.rs
  crates/types/src/field_lines.rs
  crates/types/src/field_marks.rs
  crates/types/src/line_data.rs
  crates/types/src/planned_path.rs
  crates/vision/src/calibration_measurement_provider.rs
  crates/vision/src/field_border_detection.rs
  crates/vision/src/line_detection.rs
  tools/twix/src/panels/image/overlays/field_border.rs
  tools/twix/src/panels/image/overlays/line_detection.rs
  tools/twix/src/panels/map/layers/line_correspondences.rs
  tools/twix/src/panels/map/layers/lines.rs
Labels: is:Refactoring

#1252 Tune outdoor field
  etc/parameters/nao_location
  etc/parameters/rc24_indoor/default.json
  etc/parameters/rc24_outdoor/default.json
  etc/parameters/rc24b/default.json
  etc/parameters/rc24c/default.json
  etc/parameters/rc24d/default.json
  etc/parameters/rc24e/default.json
Labels: ParameterChangesOnly

#1241 refactor `kick_target_provider`, disable obstacle detection for kick off
  crates/control/src/kick_target_provider.rs
  crates/types/src/kick_target.rs
Labels: RC24

#1258 Tune walking
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1261 Minimum Feet Width
  crates/filtering/src/mean_clustering.rs
  crates/types/src/detected_feet.rs
  crates/vision/src/feet_detection.rs
  etc/parameters/default.json
Labels: cat:Vision

#1268 fixed all standUpMotions for RC24
  etc/motions/stand_up_back.json
  etc/motions/stand_up_front.json
  etc/motions/stand_up_sitting.json
Labels: cat:Motion, RC24

#1201 Horizontal segments
  crates/projection/src/horizon.rs
  crates/types/src/image_segments.rs
  crates/types/src/ycbcr422_image.rs
  crates/vision/src/image_segmenter.rs
  crates/vision/src/segment_filter.rs
  etc/parameters/default.json
  tools/twix/src/panels/image_segments.rs
Labels: cat:Vision, RC24

#1260 Generalize Line Detection
  Cargo.lock
  Cargo.toml
  crates/linear_algebra/Cargo.toml
  crates/linear_algebra/src/framed.rs
  crates/linear_algebra/src/point.rs
  crates/vision/src/line_detection.rs
  crates/vision/src/line_detection/checks.rs
  crates/vision/src/line_detection/iter_if.rs
  crates/vision/src/line_detection/map_segments.rs
  crates/vision/src/line_detection/segment.rs
  crates/vision/src/line_detection/segment_merger.rs
  etc/parameters/default.json
  tools/twix/Cargo.toml
Labels: cat:Vision

#1271 Calibrate cameras
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, calibration:Manual

#1272 Tune Vision Field Indoor (E)
  etc/parameters/rc24_indoor/default.json
Labels: ParameterChangesOnly

#1274 Stricter segment selection in line detection
  crates/vision/src/line_detection/checks.rs
Labels: cat:Vision

#1273 Length segment
  crates/vision/src/feet_detection.rs
  etc/parameters/default.json
Labels: cat:Vision

#1281 Calibrate cameras
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00029.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, calibration:Manual

#1280 (Actually not) Fix segments ending on limbs (but refactor)
  crates/geometry/src/line.rs
  crates/types/src/limb.rs
  crates/vision/src/image_segmenter.rs
Labels: cat:Vision

#1283 More Score per Good Match
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1294 Change visual referee paramalams to fix false negatives
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1297 Fix using incorrect line segments in image
  crates/vision/src/line_detection.rs
Labels: tools:Debug Tooling, is:Bugfix

#1295 Introduce circle radius offset and increase it.
  crates/control/src/rule_obstacle_composer.rs
  etc/parameters/default.json
Labels: cat:Behavior, is:Refactoring

#1301 reset whistle in set ball position when penalized for motion in set
  crates/control/src/game_controller_state_filter.rs
Labels: cat:Behavior

#1286 Calibrate cameras for match vs SPQR
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
Labels: ParameterChangesOnly, calibration:Manual

#1308 Stop horizontal segments at uppermost limb segment
  crates/vision/src/image_segmenter.rs
  etc/parameters/default.json
Labels: cat:Vision, RC24

#1304 Actually score goals
  crates/control/src/kick_selector.rs
Labels: is:Bugfix

#1307 clamped wrongly in opponent kickoff
  crates/control/src/behavior/support.rs
Labels: cat:Behavior

#1313 Tune walking
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1315 Fix time elapsed
  crates/control/src/foot_bumper_filter.rs
Labels: is:Bugfix

#1316 Increase `foot_z_offset`
  etc/parameters/default.json
Labels: ParameterChangesOnly, RC24

#1312 Adderall
  etc/parameters/default.json
Labels: cat:Behavior, ParameterChangesOnly, RC24

#1319 Draw segments in line detection overlay
  crates/types/src/image_segments.rs
  crates/vision/src/line_detection.rs
  crates/vision/src/line_detection/checks.rs
  crates/vision/src/line_detection/map_segments.rs
  crates/vision/src/line_detection/segment.rs
  crates/vision/src/line_detection/segment_merger.rs
  tools/twix/src/panels/image/overlays/line_detection.rs
Labels: cat:Vision, tools:Debug Tooling, tools:Tooling

#1327 Camera calibration hulks vs bhuman
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, calibration:Manual

#1309 add whistle fake in simulator for opponent kickoff
  crates/code_generation/src/cyclers.rs
  crates/hulk_behavior_simulator/build.rs
  crates/hulk_behavior_simulator/src/fake_data.rs
  crates/hulk_behavior_simulator/src/robot.rs
  crates/hulk_behavior_simulator/src/simulator.rs
  crates/hulk_behavior_simulator/src/state.rs
  crates/types/src/buttons.rs
  tests/behavior/golden_goal_opponent_kickoff.lua
  tests/behavior/ingamepenalty_attacking.lua
  tests/behavior/ingamepenalty_defending.lua
Labels: tools:Tooling

#1320 Draw segment edges in image segmenter overlay
  tools/twix/src/panels/image_segments.rs
Labels: cat:Vision, tools:Debug Tooling, tools:Tooling

#1230 Also consider SubState::PenaltyKick and kicking_team for keeper localization
  crates/control/src/localization.rs
Labels: cat:Localization

#1330 Small improvements in line detection
  Cargo.lock
  crates/vision/src/line_detection.rs
  etc/parameters/default.json
  tools/twix/Cargo.toml
  tools/twix/src/panels/image/overlays/line_detection.rs
  tools/twix/src/panels/image_segments.rs
Labels: cat:Vision, tools:Debug Tooling, tools:Tooling

#1336 Du Pfeife
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/initial.rs
  crates/control/src/behavior/intercept_ball.rs
  crates/control/src/behavior/look_around.rs
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/search.rs
  crates/control/src/behavior/stand.rs
  crates/control/src/behavior/support.rs
  crates/control/src/filtered_game_controller_state_timer.rs
  crates/control/src/game_controller_filter.rs
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/search_suggestor.rs
  crates/control/src/world_state_composer.rs
  crates/hulk_behavior_simulator/src/state.rs
  crates/types/src/filtered_game_controller_state.rs
  crates/types/src/game_controller_state.rs
Labels: cat:Behavior

#1340 Add kick off ball obstacle
  crates/control/src/rule_obstacle_composer.rs
  etc/parameters/default.json
Labels: cat:Behavior

#1335 Localization motion in standby
  crates/control/src/localization.rs
Labels: ParameterChangesOnly, RC24

#1343 vision tuning for rc24 indoor field
  etc/parameters/rc24_indoor/default.json
Labels: ParameterChangesOnly

#1342 Kick positions
  crates/control/src/kick_selector.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Motion

#1338 fix foot leveling, tune parameters
  crates/walking_engine/src/foot_leveling.rs
  etc/parameters/default.json
Labels: is:Bugfix

#1346 Add horizontal edge threshold slider to vision tuner
  tools/twix/src/panels/vision_tuner.rs
Labels: tools:Debug Tooling, is:Easy

#1349 Less activations to activate foot bumper obstacles
  etc/parameters/default.json
Labels: cat:Behavior

#1351 Fix feet detection panel
  tools/twix/src/panels/map/layers/feet_detection.rs
Labels: tools:Tooling

#1350 Reduce minimum x of Midfielders and StrikerSupporter
  etc/parameters/default.json
Labels: cat:Behavior, ParameterChangesOnly

#1356 Vision parameters for outdoor
  etc/parameters/rc24_outdoor/default.json
Labels: ParameterChangesOnly

#1357 Wide stance improvements
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/head.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Behavior, ParameterChangesOnly

#1337 Remote control fixes
  crates/control/src/motion/head_motion.rs
  crates/types/src/players.rs
  etc/parameters/default.json
  tools/twix/src/panels/remote.rs
Labels: tools:Debug Tooling, is:Bugfix

#1363 Camera Calibration
  etc/parameters/head.P0000074A03S85B00016.json
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00029.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, calibration:Manual

#1362 Tune feet detection
  etc/parameters/default.json
  etc/parameters/rc24_outdoor/default.json
Labels: ParameterChangesOnly, mit Qualitätsgarantie

#1369 Camera calibration RoboÉireann
  etc/parameters/head.P0000074A03S85B00016.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00023.json
  etc/parameters/head.P0000074A09S31C00029.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, calibration:Manual

#1370 Indoor field tuning
  etc/parameters/rc24_indoor/default.json
Labels: ParameterChangesOnly

#1378 Decrease Midfielder defending position x
  etc/parameters/default.json
Labels: cat:Behavior, ParameterChangesOnly

#1380 Adderall but with restraints
  crates/control/src/behavior/defend.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
  tests/behavior/passive_defender_positioning.lua
Labels: cat:Behavior, RC24

#1328 tune walking shorter
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1300 Add `defender_distance_to_be_aligned`
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/search.rs
  crates/control/src/behavior/support.rs
  crates/control/src/behavior/walk_to_kick_off.rs
  crates/control/src/behavior/walk_to_penalty_kick.rs
  crates/control/src/behavior/walk_to_pose.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Behavior, RC24

#1385 Need always only two contacts for Footbumper
  crates/control/src/foot_bumper_filter.rs
  crates/types/src/foot_bumper_values.rs
  etc/parameters/default.json
Labels: cat:Behavior

#1386 Refactor vision tuner
  tools/twix/src/panels/vision_tuner.rs
Labels: tools:Debug Tooling, is:Easy, is:Refactoring
