Repository HULKs/hulk, pull requests merged in 2024-10, with the labels that each got.

#1450 migrate to ghcr.io package registry
  .github/workflows/ci-image.yml
  .github/workflows/pull-request.yml
  tools/ci/github-runners/Containerfile
  tools/ci/github-runners/README.md
  tools/ci/github-runners/actions-runner.yaml
  tools/ci/github-runners/docker-compose.yml
Labels: tools:CI

#1452 Run CI workflow on github runners
  .github/workflows/ci-image.yml
Labels: tools:CI

#1429 Clean up construct_*_filtered_game_state
  crates/control/src/game_controller_state_filter.rs
Labels: cat:Filtering, is:Refactoring

#1454 Remove step for setup of HULKs hosted registry
  tools/ci/github-runners/README.md
Labels: Documentation

#1455 Use github-hosted container image in documentation CI
  .github/workflows/documentation.yml
Labels: tools:CI

#1446 Update docs node
  docs/framework/node.drawio
  docs/framework/node.drawio-dark.png
  docs/framework/node.drawio-light.png
  docs/framework/node.drawio.png
  docs/framework/nodes.md
Labels: Documentation

#1441 OS Docs
  docs/operating_system/linux.md
  docs/operating_system/overview.md
Labels: Documentation

#1439 Update docs for walking
  crates/control/src/behavior/intercept_ball.rs
  crates/control/src/behavior/node.rs
  crates/control/src/motion/step_planner.rs
  crates/control/src/motion/walk_manager.rs
  crates/types/src/lib.rs
  crates/types/src/parameters.rs
  crates/types/src/step.rs
  crates/types/src/walk_command.rs
  crates/walking_engine/src/anatomic_constraints.rs
  crates/walking_engine/src/feet.rs
  crates/walking_engine/src/kick_steps.rs
  crates/walking_engine/src/lib.rs
  crates/walking_engine/src/mode.rs
  crates/walking_engine/src/mode/catching.rs
  crates/walking_engine/src/mode/kicking.rs
  crates/walking_engine/src/mode/standing.rs
  crates/walking_engine/src/mode/starting.rs
  crates/walking_engine/src/mode/stopping.rs
  crates/walking_engine/src/mode/walking.rs
  crates/walking_engine/src/parameters.rs
  crates/walking_engine/src/step_plan.rs
  docs/robotics/behavior/overview.md
  docs/robotics/motion/overview.md
  docs/robotics/motion/step_planning.md
  docs/robotics/motion/walking.md
  mkdocs.yml
  tools/twix/src/panels/map/layers/walking.rs
  tools/twix/src/panels/remote.rs
Labels: Documentation, is:Refactoring

#1459 Update CI image to Rust 1.81.0
  .github/workflows/ci-image.yml
  .github/workflows/documentation.yml
  .github/workflows/pull-request.yml
  crates/hulk_behavior_simulator/src/lib.rs
  crates/hulk_behavior_simulator/src/simulator.rs
  tools/ci/github-runners/Containerfile
  tools/twix/src/panels/remote.rs
Labels: tools:CI

#1464 Use incremental profile for cargo test
  .github/workflows/pull-request.yml
Labels: tools:CI

#1465 tune field color after return from Eindhoven
  etc/parameters/smd/default.json
Labels: ParameterChangesOnly

#1427 Remove `Uncertain` kind from Team type
  crates/control/src/ball_state_composer.rs
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/stand.rs
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/rule_obstacle_composer.rs
  crates/control/src/search_suggestor.rs
  crates/spl_network_messages/src/game_controller_state_message.rs
  crates/types/src/filtered_game_controller_state.rs
  crates/types/src/filtered_game_state.rs
  tests/behavior/demonstration.lua
Labels: is:Refactoring
