Repository HULKs/hulk, pull requests merged in 2024-11, with the labels that each got.

#1480 fix center circle violation
  crates/control/src/rule_obstacle_composer.rs
Labels: cat:Behavior, is:Bugfix

#1482 update remote compile documentation
  docs/tooling/gnome-settings-vpn-manual.png
  docs/tooling/pepsi.md
Labels: Documentation

#1504 Put openvino installation in sub-box
  docs/setup/development_environment.md
Labels: Documentation

#1512 Fix SSH password prompt appearing with robocupper image
  crates/nao/src/lib.rs
Labels: tools:Tooling

#1526 Remove `unwrap` call
  crates/nao/src/lib.rs
Labels: is:Easy, is:Refactoring

#1527 Make twix user config keys optional
  tools/twix/src/configuration.rs
  tools/twix/src/configuration/keys.rs
  tools/twix/src/configuration/merge.rs
Labels: tools:Debug Tooling
