Repository HULKs/hulk, pull requests merged in 2024-05, with the labels that each got.

#1017 bring naos home
  etc/parameters/nao_location
Labels: ParameterChangesOnly

#1008 Add Why to PR template
  .github/pull_request_template.md
Labels: is:Orga

#1005 run checks on merge_group trigger
  .github/workflows/pull-request.yml
Labels: tools:CI

#1029 Smaller Locking Scopes of HuLA interfacing
  crates/hulk_nao/src/hardware_interface.rs
  crates/hulk_nao/src/hula_wrapper.rs
Labels: cat:Framework, is:Bug, is:EasyWin

#1031 twix: bind CTRL+[arrow keys] to move focus
  tools/twix/default.toml
Labels: tools:Debug Tooling

#1032 Fix capitalization in error messages
  tools/twix/src/configuration/keys.rs
Labels: tools:Debug Tooling

#1030 Speed up stand up back
  etc/parameters/default.json
Labels: cat:Motion

#1041 Smd vision
  etc/parameters/smd/default.json
Labels: cat:Vision

#1035 camera matrix calibration of 40
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly
