Repository HULKs/hulk, pull requests merged in 2024-04, with the labels that each got.

#794 remove the localization recorder again...
  etc/parameters/default.json
Labels: GO24

#795 increase `foot_pressure_threshold` to improve walking of 31
  etc/parameters/head.P0000074A06S9A900006.json
Labels: ParameterChangesOnly

#800 Today's Therapy Session: Panics
  crates/code_generation/src/execution.rs
Labels: cat:Framework, GO24

#792 Improvements to Vision Tuner
  tools/twix/src/panels/vision_tuner.rs
Labels: tools:Tooling, GO24

#810 Parallel Camera Access
  crates/hulk_nao/src/camera.rs
Labels: GO24

#812 Increase penalty box size to prevent keeper getting stuck
  crates/control/src/rule_obstacle_composer.rs
  etc/parameters/default.json
  tools/behavior_simulator/src/cycler.rs
Labels: cat:Behavior, GO24

#813 Add tests for each behavior file
  tools/behavior_simulator/tests/scenarios.rs
Labels: tools:CI, GO24

#820 deprecate meta-hulks in favor of meta-nao
  .github/workflows/ci-image.yml
Labels: GO24

#821 Jetzt aber wirklich
  tools/ci/github-runners/v3/Dockerfile
Labels: GO24

#805 Increase turning speed to decrease head-wobble
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#822 Allow transition from finished to initial
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/primary_state_filter.rs
  crates/types/src/filtered_game_state.rs
Labels: cat:Behavior, GO24

#823 Repair Webots etc.
  crates/code_generation/src/cyclers.rs
  crates/hulk/Cargo.toml
  crates/hulk_nao/Cargo.toml
Labels: GO24

#830 calibrate some cameras
  etc/parameters/head.P0000074A06S9A900006.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
Labels: GO24

#828 Bump pepsi version
  Cargo.lock
  tools/pepsi/Cargo.toml
Labels: tools:Tooling

#825 Stay in Calibration
  crates/control/src/primary_state_filter.rs
Labels: is:Bug, is:EasyWin, GO24

#839 Fix sdk version
  Cargo.lock
  crates/constants/src/lib.rs
  tools/pepsi/Cargo.toml
Labels: GO24

#851 set default location to GO24
  etc/parameters/go24/default.json
  etc/parameters/nao_location
Labels: ParameterChangesOnly, GO24

#852 Apply Poppinga'sche Vorzeichenmethode
  crates/types/src/interpolated.rs
Labels: cat:Vision, GO24

#854 rotate slower when searching for the ball
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#857 Add new robot numbers to twix
  tools/twix/src/main.rs
Labels: tools:Debug Tooling, GO24

#868 Disable detection cycler by feature flag
  crates/code_generation/src/execution.rs
  crates/hulk_replayer/Cargo.toml
  crates/hulk_replayer/build.rs
  crates/hulk_replayer/src/main.rs
  crates/hulk_replayer/src/replayer.rs
  crates/hulk_replayer/src/statistics.rs
Labels: cat:Framework, GO24

#873 Don't compress rsync stream
  crates/nao/src/lib.rs
Labels: GO24

#876 Set correct nao location
  etc/parameters/nao_location
Labels: ParameterChangesOnly, GO24

#874 Wir ham uns das mal angeschaut und gemerkt dass das garnicht mal so geil ist wenn man zwei meter rückwärts läuft, also wurde die hybrid alignment distance runtergesetzt sodass wir uns erst später drehen
  etc/parameters/default.json
Labels: cat:Behavior, test:Field Needed, GO24

#870 Do not unwrap required inputs during recording
  crates/code_generation/src/cyclers.rs
Labels: cat:Framework, GO24

#856 added save function to enum_plot_panel
  tools/twix/src/panels/enum_plot.rs
Labels: GO24

#871 Plot panel
  tools/twix/src/panels/enum_plot.rs
Labels: GO24

#884 calibrate 41
  etc/parameters/head.P0000074A10S41M00040.json
Labels: ParameterChangesOnly, GO24

#885 calibrate 40
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO24

#893 Schnagger
  crates/hulk_replayer/src/replayer.rs
Labels: tools:Tooling, GO24

#895 Panikmache
  crates/code_generation/src/execution.rs
Labels: cat:Framework, GO24

#900 Consider Ready to Penalized transition
  crates/control/src/localization.rs
Labels: cat:Localization, GO24

#902 Fix incorrect parameter path
  crates/control/src/game_controller_filter.rs
Labels: GO24

#899 Use localization lines in Twix panel for higher replay framerate
  tools/twix/src/panels/map/layers/lines.rs
  tools/twix/src/panels/map/mod.rs
Labels: tools:Tooling, GO24

#901 Discard hypothesis when losing ground contact
  crates/control/src/localization.rs
Labels: cat:Localization, GO24

#910 Tune standing up
  etc/motions/stand_up_sitting.json
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#909 Bump OS and pepsi version
  Cargo.lock
  crates/constants/src/lib.rs
  tools/pepsi/Cargo.toml
Labels: ParameterChangesOnly, GO24

#914 disable object detction by default
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#920 Reduce ball validity
  etc/parameters/default.json
Labels: cat:BallSearch

#915 Tune odometry
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#927 scale border_strip_width from 0.7 to 0.9
  etc/parameters/default.json
Labels: GO24

#931 increase angle_distance_weight
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#932 Allow detecting shorter lines in bottom camera
  etc/parameters/default.json
Labels: cat:Vision, ParameterChangesOnly, GO24

#935 macht da jemand eigentlich irgendwann ein absolute draus?
  crates/geometry/src/line.rs
Labels: GO24

#941 Focus node on creation of newly-created tab
  tools/twix/src/main.rs
Labels: tools:Debug Tooling

#950 Pepsi pregame: set network before restarting
  tools/pepsi/src/pre_game.rs
Labels: tools:Tooling, GO24

#952 Tuned Turn Parameters in walking
  etc/parameters/default.json
Labels: GO24

#955 modified odometry
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#956 Record SplNetwork by default
  tools/pepsi/src/pre_game.rs
Labels: tools:Tooling

#951 Jockel Gockel
  crates/control/src/kick_selector.rs
Labels: GO24

#957 Odometryaus Maxis Träumen
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#943 Side and Turn paramters
  etc/parameters/default.json
Labels: GO24

#959 Change image segmenter threshold to 20 for bottom
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO24

#963 Camera calibration
  etc/parameters/head.P0000074A04S8CP00037.json
  etc/parameters/head.P0000074A06S9A900006.json
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO24

#967 how to wear a fedora
  docs/setup/main_setup.md
Labels: Documentation

#971 Replayer UI v3
  Cargo.lock
  Cargo.toml
  crates/hulk_replayer/Cargo.toml
  crates/hulk_replayer/src/coordinate_systems.rs
  crates/hulk_replayer/src/frames.rs
  crates/hulk_replayer/src/labels.rs
  crates/hulk_replayer/src/main.rs
  crates/hulk_replayer/src/replayer.rs
  crates/hulk_replayer/src/ticks.rs
  crates/hulk_replayer/src/timeline.rs
  crates/hulk_replayer/src/user_interface.rs
  crates/hulk_replayer/src/window.rs
  docs/tooling/recording_and_replay.md
  tools/annotato/src/widgets/bounding_box_annotator.rs
  tools/annotato/src/widgets/path_row.rs
  tools/twix/src/completion_edit.rs
  tools/twix/src/panels/enum_plot.rs
  tools/twix/src/panels/map/mod.rs
Labels: cat:Replay, tools:Tooling
