Repository HULKs/hulk, pull requests merged in 2024-03, with the labels that each got.

#740 Bump twix version after Coordinate System Rollout
  Cargo.lock
  tools/twix/Cargo.toml
Labels: tools:Debug Tooling

#738 Context Privacy 2
  crates/control/src/foot_bumper_filter.rs
  crates/control/src/visual_referee_filter.rs
  crates/control/src/whistle_filter.rs
Labels: is:Cleanup

#747 Temporary download names
  crates/repository/src/lib.rs
Labels: tools:SDK, tools:Tooling

#742 Fix Penalty Shootout
  crates/control/src/game_controller_state_filter.rs
Labels: cat:Filtering, is:Bug

#770 Run dmesg with sudo
  crates/nao/src/lib.rs
Labels: tools:Tooling

#777 Update replay docs to reflect usage changes
  docs/tooling/overview.md
  docs/tooling/recording_and_replay.md
  mkdocs.yml
Labels: cat:Replay, Documentation

#774 Interpret EOF errors as soft errors
  crates/framework/src/recording_index.rs
Labels: cat:Framework, tools:Tooling
