Repository HULKs/hulk, pull requests merged in 2025-06, with the labels that each got.

#1860 Served hot
  Cargo.lock
  crates/bevyhavior_simulator/Cargo.toml
  crates/bevyhavior_simulator/src/recorder.rs
  crates/bevyhavior_simulator/src/server.rs
  crates/bevyhavior_simulator/src/simulator.rs
Labels: cat:Behavior, tools:Debug Tooling, is:EasyWin

#1863 Refactor keybind type
  docs/tooling/twix.md
  tools/twix/src/configuration/keybind_plugin.rs
  tools/twix/src/configuration/keys.rs
Labels: tools:Debug Tooling, is:Refactoring

#1849 fix injected motion command
  crates/control/src/motion/motor_commands_optimizer.rs
  crates/types/src/motion_command.rs
Labels: is:Bugfix

#1864 Impl PathSerde for serde_json::Value
  Cargo.lock
  crates/path_serde/Cargo.toml
  crates/path_serde/src/not_supported.rs
  services/aliveness/Cargo.lock
  services/hula/Cargo.lock
Labels: tools:Debug Tooling

#1872 Fix new clippy lint
  crates/control/src/ready_signal_detection_filter.rs
Labels: is:Cleanup, is:Easy

#1870 upgrade to 9.0.1
  hulk.toml
Labels: RoboCup 2025 ⚽

#1447 Twix panel to save automatic calibration values to the repo
  Cargo.lock
  crates/control/src/calibration_controller.rs
  tools/twix/Cargo.toml
  tools/twix/src/main.rs
  tools/twix/src/panels/automatic_camera_calibration_export.rs
  tools/twix/src/panels/manual_camera_calibration.rs
  tools/twix/src/panels/mod.rs
Labels: cat:Calibration, tools:Debug Tooling, calibration:Automatic

#1852 Refactor: Consolidate motor_commands_optimizer into motor_commands_collector
  crates/control/src/motion/command_sender.rs
  crates/control/src/motion/mod.rs
  crates/control/src/motion/motor_commands_collector.rs
  crates/hulk_manifest/src/lib.rs
  docs/robotics/motion/overview.md
Labels: is:Refactoring

#1879 Default to jpg in twix
  Cargo.lock
  tools/twix/Cargo.toml
  tools/twix/src/panels/image/mod.rs
Labels: tools:Debug Tooling

#1884 Don't crash twix on unknown panel type
  Cargo.lock
  tools/twix/Cargo.toml
  tools/twix/src/main.rs
  tools/twix/src/selectable_panel_macro.rs
Labels: tools:Debug Tooling

#1887 Draw more field lines
  Cargo.lock
  crates/control/src/camera_matrix_calculator.rs
  crates/types/src/field_dimensions.rs
  tools/twix/Cargo.toml
  tools/twix/src/panels/image/overlay.rs
  tools/twix/src/panels/image/overlays/field_lines.rs
  tools/twix/src/panels/image/overlays/mod.rs
Labels: tools:Debug Tooling

#1862 stand up counter
  crates/control/src/motion/motion_selector.rs
  crates/types/src/motion_selection.rs
Labels: RoboCup 2025 ⚽
