Repository HULKs/hulk, pull requests merged in 2025-05, with the labels that each got.

#1831 Teamball in heatmap
  crates/control/src/search_suggestor.rs
  crates/control/src/team_ball_receiver.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: cat:BallSearch, RoboCup 2025 ⚽

#1823 Add individual and total node duration measurements
  crates/code_generation/src/cyclers.rs
  crates/code_generation/src/structs.rs
  crates/source_analyzer/src/structs.rs
Labels: cat:Framework, tools:Debug Tooling

#1841 Add awk to fedora dependencies
  docs/setup/development_environment.md
Labels: Documentation

#1844 Fix clippy lints for 0.1.87
  crates/control/src/behavior/support.rs
  crates/control/src/primary_state_filter.rs
  crates/source_analyzer/src/struct_hierarchy.rs
Labels: is:Cleanup

#1846 Add scatter points in plot
  tools/twix/src/panels/plot.rs
Labels: tools:Debug Tooling

#1782 Pushing kicking team filtering
  crates/bevyhavior_simulator/build.rs
  crates/bevyhavior_simulator/src/autoref.rs
  crates/bevyhavior_simulator/src/bin/ball_search.rs
  crates/bevyhavior_simulator/src/bin/demonstration.rs
  crates/bevyhavior_simulator/src/bin/deny_keeper_ballsearch.rs
  crates/bevyhavior_simulator/src/bin/goal_kicks.rs
  crates/bevyhavior_simulator/src/bin/golden_goal_striker_penalized.rs
  crates/bevyhavior_simulator/src/bin/ingame_penalty_kick.rs
  crates/bevyhavior_simulator/src/bin/ingame_penalty_kick_opponent.rs
  crates/bevyhavior_simulator/src/bin/ingame_penalty_kick_opponent_with_kick.rs
  crates/bevyhavior_simulator/src/bin/ingame_penalty_kick_striker_penalized.rs
  crates/bevyhavior_simulator/src/bin/kick_in.rs
  crates/bevyhavior_simulator/src/bin/kicking_team_filtering.rs
  crates/bevyhavior_simulator/src/bin/replacement_keeper.rs
  crates/bevyhavior_simulator/src/bin/two_replacement_keepers.rs
  crates/bevyhavior_simulator/src/game_controller.rs
  crates/control/src/ball_state_composer.rs
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/kicking_team_filter.rs
  crates/control/src/lib.rs
  crates/hulk_manifest/src/lib.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Filtering, RoboCup 2025 ⚽

#1848 Fix rsync to remote when using multiple worktrees
  scripts/remote_workspace
Labels: tools:Tooling, is:Bugfix

#1857 Use struct instead of tuple for dribble path plan
  crates/control/src/behavior/dribble.rs
  crates/control/src/behavior/node.rs
  crates/control/src/dribble_path_planner.rs
  crates/control/src/time_to_reach_kick_position.rs
  crates/types/src/dribble_path_plan.rs
  crates/types/src/lib.rs
Labels: is:Easy, is:Refactoring
