Repository HULKs/hulk, pull requests merged in 2025-03, with the labels that each got.

#1654 use original bevy_panorbit_camera dependency
  Cargo.lock
  Cargo.toml
Labels: mio

#1586 Upload source distribution
  crates/nao/src/lib.rs
  crates/repository/src/upload.rs
Labels: tools:Tooling

#1666 Fix CI for documentation
  .github/workflows/documentation.yml
Labels: Documentation

#1655 I am speed
  Cargo.lock
  Cargo.toml
  tools/mio/Cargo.toml
Labels: mio

#1673 Fix enum plot crashes
  tools/twix/src/change_buffer.rs
Labels: tools:Debug Tooling, is:Bugfix

#1658 Optional Shadows for mio
  Cargo.lock
  tools/mio/Cargo.toml
  tools/mio/src/fps.rs
  tools/mio/src/main.rs
  tools/mio/src/shadow_toggle.rs
  tools/mio/src/ui.rs
Labels: mio

#1674 Add coordinate indicator to image panel
  tools/twix/src/panels/image/mod.rs
Labels: tools:Debug Tooling

#1681 Make clippy warnings errors in CI
  .github/workflows/pull-request.yml
  tools/annotato/src/user_toml.rs
  tools/twix/src/configuration/keys.rs
Labels: tools:CI

#1685 Replayer: communicate hardware IDs over communication
  crates/code_generation/src/execution.rs
Labels: cat:Replay

#1684 Replace reached thresholds for kickdecisions with ranges
  crates/control/src/behavior/dribble.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: GO25

#1682 Normalize foot lift increase
  Cargo.lock
  crates/control/src/motion/walking_engine.rs
  crates/types/Cargo.toml
  crates/types/src/parameters.rs
  crates/types/src/step.rs
  crates/walking_engine/Cargo.toml
  crates/walking_engine/src/lib.rs
  crates/walking_engine/src/step_plan.rs
  etc/parameters/default.json
Labels: cat:Walking, GO25

#1688 Optimize energy optimization
  crates/control/src/motion/motor_commands_collector.rs
  crates/energy_optimization/src/current_minimizer.rs
  crates/energy_optimization/src/parameters.rs
  etc/parameters/default.json
Labels: is:EasyWin, GO25

#1692 fixed standup front
  etc/parameters/default.json
Labels: GO25

#1699 Host local replay on ipv4
  crates/hulk_replayer/src/replayer.rs
Labels: GO25

#1701 Document Eye Colors
  docs/robotics/behavior/overview.md
Labels: GO25

#1690 Expose uncorrected camera matrix
  crates/control/src/camera_matrix_calculator.rs
  etc/parameters/default.json
Labels: GO25

#1693 Tune walking
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO25

#1702 Keepermotien weniger Knackable
  etc/motions/keeper_jump_right.json
Labels: GO25

#1703 Faster Stanup after wideStance
  etc/motions/wide_stance.json
Labels: GO25

#1700 Expose remaining time in GameControllerState
  crates/bevyhavior_simulator/src/game_controller.rs
  crates/control/src/game_controller_filter.rs
  crates/control/src/game_controller_state_filter.rs
  crates/types/src/filtered_game_controller_state.rs
  crates/types/src/game_controller_state.rs
Labels: GO25

#1706 change HeatMap::map from nalgebra to ndarray
  Cargo.lock
  crates/bevyhavior_simulator/Cargo.toml
  crates/bevyhavior_simulator/src/bin/corner_kicks.rs
  crates/control/src/search_suggestor.rs
  crates/hulk/Cargo.toml
  crates/hulk_imagine/Cargo.toml
  crates/hulk_replayer/Cargo.toml
  crates/hulk_webots/Cargo.toml
  crates/path_serde/Cargo.toml
  crates/path_serde/src/not_supported.rs
  tools/twix/Cargo.toml
  tools/twix/src/panels/map/layers/ball_search_heatmap.rs
Labels: cat:BallSearch, GO25

#1709 calibration 34 40 25 29 28 27 41
  etc/parameters/go25/head.P0000074A09S28J00025.json
  etc/parameters/go25/head.P0000074A09S31C00028.json
  etc/parameters/go25/head.P0000074A09S31C00037.json
  etc/parameters/go25/head.P0000074A09S31T00003.json
  etc/parameters/go25/head.P0000074A10S41M00040.json
  etc/parameters/go25/head.P0000074A10S41M00047.json
  etc/parameters/go25/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO25

#1399 More dense candidates
  crates/vision/src/perspective_grid_candidates_provider.rs
  etc/parameters/default.json
  tools/twix/src/panels/image/overlays/ball_detection.rs
  tools/twix/src/panels/image/overlays/field_border.rs
Labels: cat:Vision, GO25

#1710 Loser locks in on hypothetical ball positions
  crates/control/src/behavior/lost_ball.rs
Labels: GO25

#1722 slower backwards walking
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO25

#1724 anti x legs
  etc/parameters/body.P0000073A19S31C00037.json
Labels: ParameterChangesOnly

#1732 Tune odometry and walking
  crates/control/src/motion/step_planner.rs
  etc/parameters/default.json
Labels: ParameterChangesOnly, mit Qualitätsgarantie, GO25

#1734 StandUp better
  crates/control/src/motion/stand_up_back.rs
  crates/control/src/motion/stand_up_front.rs
  etc/motions/stand_up_back.json
  etc/parameters/default.json
Labels: GO25

#1736 Fix various FeetDetection bugs
  crates/filtering/src/mean_clustering.rs
  crates/vision/src/feet_detection.rs
Labels: GO25

#1698 Eat larger patches
  etc/parameters/default.json
Labels: cat:Vision, GO25

#1737 Angle to specify kickoff direction
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/walk_to_kick_off.rs
  crates/control/src/kick_selector.rs
  crates/types/src/kick_decision.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: GO25

#1740 caliobration 34 35 37 38 39 40 41
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO25

#1739 CloseAll panels in Twix
  tools/twix/config_default.toml
  tools/twix/src/configuration/keys.rs
  tools/twix/src/main.rs
Labels: GO25

#1747 set `kick_off_kick_strength = 1`
  etc/parameters/default.json
Labels: ParameterChangesOnly

#1748 calibration 33 32
  etc/parameters/head.P0000074A09S31C00023.json
Labels: ParameterChangesOnly, GO25

#1742 Remember localization when penalized in Set
  crates/control/src/localization.rs
Labels: cat:Localization

#1750 Use correct segment position for horizontal segment filtering
  crates/vision/src/segment_filter.rs
  etc/parameters/default.json
Labels: GO25

#1751 Tune Segment Threshold
  etc/parameters/default.json
Labels: GO25

#1752 calibrate 37 40 23 34 38 41 39 32
  etc/parameters/head.P0000074A03S85B00016.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO25

#1753 Run param-alarm in pregame
  Cargo.lock
  tools/pepsi/Cargo.toml
  tools/pepsi/src/cargo/environment.rs
  tools/pepsi/src/pre_game.rs
Labels: tools:Tooling, GO25

#1761 Accept broken recording index
  crates/framework/src/recording_index.rs
Labels: GO25

#1670 Implement substitutions using the deploy.toml
  Cargo.lock
  crates/argument_parsers/src/lib.rs
  deploy.toml.example
  tools/pepsi/Cargo.toml
  tools/pepsi/src/deploy_config.rs
  tools/pepsi/src/player_number.rs
  tools/pepsi/src/post_game.rs
  tools/pepsi/src/pre_game.rs
Labels: tools:Tooling, GO25

#1743 Fix side bonus
  crates/control/src/motion/step_planner.rs
  etc/parameters/default.json
Labels: GO25

#1762 reduce turn apex increase
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO25

#1763 Stay Penalized while no ground contact
  crates/control/src/primary_state_filter.rs
Labels: GO25

#1765 Collect all penalties for challenge shield
  crates/spl_network_messages/src/game_controller_state_message.rs
Labels: GO25

#1767 Calibratet 38 34 39 40 37 41 23
  etc/parameters/head.P0000074A03S85B00016.json
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO25

#1769 Tighten individual cycler execution time bounds
  crates/bevyhavior_simulator/build.rs
  crates/code_generation/src/accessor.rs
  crates/code_generation/src/cyclers.rs
  crates/hulk_manifest/src/lib.rs
  crates/source_analyzer/src/cyclers.rs
  crates/source_analyzer/src/manifest.rs
Labels: cat:Framework, GO25

#1759 Referee silence interval
  crates/code_generation/src/cyclers.rs
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/referee_pose_detection_filter.rs
  crates/control/src/role_assignment.rs
  etc/parameters/default.json
Labels: cat:Filtering, GO25

#1771 Apply overrides to both support and swing leg
  crates/walking_engine/src/kick_state.rs
  crates/walking_engine/src/kick_steps.rs
  etc/parameters/default.json
Labels: GO25

#1749 Larger Inside turns
  crates/control/src/motion/step_planner.rs
  crates/walking_engine/src/anatomic_constraints.rs
  crates/walking_engine/src/mode/catching.rs
  crates/walking_engine/src/parameters.rs
  crates/walking_engine/src/step_plan.rs
  etc/parameters/default.json
Labels: cat:Walking, GO25

#1772 Add step dependent torso tilt compensation for walking
  crates/control/src/motion/walking_engine.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Walking, GO25

#1777 Skip sending redundant loser messages
  crates/bevyhavior_simulator/src/bin/flickering_ball.rs
  crates/bevyhavior_simulator/src/robot.rs
  crates/control/src/role_assignment.rs
Labels: cat:Behavior, cat:Network, GO25

#1776 Default Field Dimensions in Mio
  tools/mio/src/parameters.rs
Labels: GO25

#1778 tune line-detection parameter
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO25

#1774 Apply stiffness loss as override to other joints
  crates/control/src/motion/walking_engine.rs
  crates/types/src/joints/body.rs
  crates/types/src/joints/leg.rs
  crates/walking_engine/src/compensate_stiffness_loss.rs
  crates/walking_engine/src/gyro_balancing.rs
  crates/walking_engine/src/lib.rs
  crates/walking_engine/src/mode/catching.rs
  crates/walking_engine/src/mode/kicking.rs
  crates/walking_engine/src/parameters.rs
  crates/walking_engine/src/step_plan.rs
  crates/walking_engine/src/step_state.rs
  etc/parameters/default.json
Labels: GO25

#1766 Bare kicking team filtering
  crates/bevyhavior_simulator/build.rs
  crates/bevyhavior_simulator/src/game_controller.rs
  crates/control/src/ball_state_composer.rs
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/stand.rs
  crates/control/src/dribble_path_planner.rs
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/kick_selector.rs
  crates/control/src/kicking_team_filter.rs
  crates/control/src/lib.rs
  crates/control/src/localization.rs
  crates/control/src/penalty_shot_direction_estimation.rs
  crates/control/src/rule_obstacle_composer.rs
  crates/control/src/search_suggestor.rs
  crates/hulk_manifest/src/lib.rs
  crates/path_serde/src/implementation.rs
  crates/spl_network_messages/headers/RoboCupGameControlData.hpp
  crates/spl_network_messages/src/game_controller_state_message.rs
  crates/spl_network_messages/src/lib.rs
  crates/types/src/filtered_game_controller_state.rs
  crates/types/src/filtered_game_state.rs
  crates/types/src/game_controller_state.rs
  crates/types/src/penalty_shot_direction.rs
  crates/types/src/world_state.rs
  etc/parameters/default.json
Labels: rules:2025, GO25

#1764 Do not use line measurements while getting up
  crates/control/src/localization.rs
  crates/types/src/stand_up.rs
Labels: GO25

#1779 Do active active vision if ball is on other field half
  crates/control/src/behavior/head.rs
Labels: cat:Behavior, AI 🧠, GO25

#1780 Larger reached x for forward kicks
  etc/parameters/default.json
Labels: GO25

#1775 Require less ready signal percepts
  etc/parameters/default.json
Labels: GO25

#1786 Walk slightly faster
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO25

#1785 Kick Tuning
  crates/control/src/motion/step_planner.rs
  crates/types/src/step.rs
  etc/parameters/default.json
Labels: GO25

#1768 anti x legs for 37
  etc/parameters/body.P0000073A19S31T00003.json
Labels: ParameterChangesOnly, GO25

#1787 Calibratet whole team without 33 35 38
  etc/parameters/head.P0000074A03S84400010.json
  etc/parameters/head.P0000074A03S85B00016.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A06S9A900006.json
  etc/parameters/head.P0000074A06S9A900031.json
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO25

#1770 fix parameter panel
  tools/twix/src/panels/parameter.rs
Labels: tools:Debug Tooling, is:Bugfix, GO25

#1790 Always execute kicks to the end
  crates/walking_engine/src/mode/kicking.rs
Labels: GO25

#1791 Add hysteresis region to defender positioning
  crates/control/src/behavior/defend.rs
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/search.rs
  crates/control/src/behavior/support.rs
  crates/control/src/behavior/walk_to_kick_off.rs
  crates/control/src/behavior/walk_to_penalty_kick.rs
  crates/control/src/behavior/walk_to_pose.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: GO25

#1792 Calibratet 21 32 33 34 37 40 38 41 35
  etc/parameters/head.P0000074A03S84400010.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A09S31C00023.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO25

#1794 Walk faster in penalty shootout
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO25

#1798 tilt more forwards
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO25

#1799 Calibratet semi final
  etc/parameters/head.P0000074A10S41M00040.json
Labels: ParameterChangesOnly, GO25

#1797 less power
  etc/parameters/default.json
Labels: ParameterChangesOnly, GO25

#1800 Parameters to fall less
  etc/parameters/default.json
Labels: GO25

#1793 More aggressive defender
  etc/parameters/default.json
Labels: GO25

#1796 Allow optional cycler state
  crates/context_attribute/src/lib.rs
  crates/source_analyzer/src/contexts.rs
Labels: cat:Framework, is:EasyWin, is:Bugfix, GO25

#1803 Make the last kick step a little to the back
  etc/parameters/default.json
Labels: GO25

#1806 Completion edit improvements
  crates/hulk_widgets/src/completion_edit.rs
  tools/twix/src/main.rs
Labels: tools:Debug Tooling, is:Bugfix

#1804 final calibration team
  etc/parameters/head.P0000074A03S84400010.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A06S9A900006.json
  etc/parameters/head.P0000074A06S9A900031.json
  etc/parameters/head.P0000074A09S31C00023.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: ParameterChangesOnly, GO25

#1811 Improve foot leveling #1809
  crates/walking_engine/src/foot_leveling.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Walking

#1808 Initial side step fix
  crates/control/src/motion/step_planner.rs
Labels: cat:Walking

#1818 Remove broken corner kicks scenario
  crates/bevyhavior_simulator/src/bin/corner_kicks.rs
Labels: is:Cleanup
