Repository HULKs/hulk, pull requests merged in 2025-07, with the labels that each got.

#1903 location smd!!!
  etc/parameters/nao_location
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#1901 remove unused parameters
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: is:Cleanup, RoboCup 2025 ⚽

#1907 Bump to rust 1.88
  tools/ci/github-runners/Containerfile
Labels: tools:CI

#1876 slower head movement for defender
  crates/control/src/motion/head_motion.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: RoboCup 2025 ⚽

#1902 Tune gyro balancing
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#1916 Tune standup
  etc/parameters/default.json
Labels: cat:Motion, RoboCup 2025 ⚽

#1914 walking slower when hot
  crates/control/src/motion/step_planner.rs
Labels: cat:MotionPlanning, cat:Walking, RoboCup 2025 ⚽

#1911 Limit turn_acceleration
  crates/walking_engine/src/mode/walking.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Walking, RoboCup 2025 ⚽

#1905 deny standup after 3 tries and ouch
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/stand_up.rs
  crates/control/src/motion/motion_selector.rs
  crates/types/src/motion_selection.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: RoboCup 2025 ⚽

#1937 Fix Image segmenter
  Cargo.lock
  crates/vision/src/image_segmenter.rs
Labels: cat:Vision

#1928 Profiling with `perf`
  crates/hulk_nao/Cargo.toml
  crates/repository/src/upload.rs
  docs/tooling/overview.md
  docs/tooling/profiling.md
  mkdocs.yml
Labels: Documentation

#1939 set location rc25
  etc/parameters/nao_location
  etc/parameters/rc25/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#1941 edit parameter stand_up_sitting
  etc/parameters/default.json
Labels: cat:Motion, ParameterChangesOnly, RoboCup 2025 ⚽

#1704 Field color labeling and decision tree
  crates/types/src/color.rs
  crates/types/src/field_color.rs
  crates/types/src/lib.rs
  crates/vision/src/field_color_tree.rs
  crates/vision/src/image_segmenter.rs
  crates/vision/src/lib.rs
  etc/parameters/default.json
  etc/parameters/smd/default.json
  tools/field_color_detection/.gitattributes
  tools/field_color_detection/.python-version
  tools/field_color_detection/best_DecisionTree_1543.joblib
  tools/field_color_detection/delete_last_trials.py
  tools/field_color_detection/extract_csv.py
  tools/field_color_detection/extract_labels.py
  tools/field_color_detection/generate_tree.py
  tools/field_color_detection/image_sampler.py
  tools/field_color_detection/label_and_train.py
  tools/field_color_detection/pyproject.toml
  tools/field_color_detection/run_optimization_pipeline.py
  tools/field_color_detection/scripts.py
  tools/field_color_detection/src/field_color_detection/__init__.py
  tools/field_color_detection/src/field_color_detection/data.py
  tools/field_color_detection/src/field_color_detection/gabor_filters.py
  tools/field_color_detection/src/field_color_detection/histogram_of_oriented_gradients.py
  tools/field_color_detection/src/field_color_detection/linear_svm.py
  tools/field_color_detection/src/field_color_detection/local_binary_pattern.py
  tools/field_color_detection/src/field_color_detection/neighboring_pixels.py
  tools/field_color_detection/src/field_color_detection/nystroem.py
  tools/field_color_detection/src/field_color_detection/objective.py
  tools/field_color_detection/src/field_color_detection/plots.py
  tools/field_color_detection/src/field_color_detection/settings.py
  tools/field_color_detection/tree_to_rust.py
  tools/field_color_detection/uv.lock
  tools/twix/src/panels/image_color_select.rs
  tools/twix/src/panels/vision_tuner.rs
Labels: cat:Calibration, cat:Vision, RoboCup 2025 ⚽

#1946 Tune catching steps
  crates/walking_engine/src/mode/catching.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Walking, RoboCup 2025 ⚽

#1936 Bevyhavior laufen
  Cargo.lock
  crates/bevyhavior_simulator/Cargo.toml
  crates/bevyhavior_simulator/build.rs
  crates/bevyhavior_simulator/src/bin/ball_search.rs
  crates/bevyhavior_simulator/src/bin/defender_positioning.rs
  crates/bevyhavior_simulator/src/bin/demonstration.rs
  crates/bevyhavior_simulator/src/bin/flickering_ball.rs
  crates/bevyhavior_simulator/src/bin/keeper_returns_after_loser.rs
  crates/bevyhavior_simulator/src/bin/kick_in.rs
  crates/bevyhavior_simulator/src/bin/kicking_team_filtering.rs
  crates/bevyhavior_simulator/src/bin/quantum_ball.rs
  crates/bevyhavior_simulator/src/fake_data.rs
  crates/bevyhavior_simulator/src/robot.rs
  crates/control/src/motion/walking_engine.rs
  crates/control/src/zero_moment_point_provider.rs
  crates/geometry/src/is_inside_polygon.rs
  crates/geometry/src/lib.rs
  crates/geometry/src/polygon.rs
  crates/hulk/build.rs
  crates/types/src/obstacle_avoiding_arms.rs
  crates/types/src/sensor_data.rs
  crates/types/src/support_foot.rs
  crates/walking_engine/src/lib.rs
  crates/walking_engine/src/mode.rs
  crates/walking_engine/src/mode/catching.rs
  etc/parameters/behavior_simulator_location/default.json
  tools/twix/src/panels/map/layers/walking.rs
Labels: cat:Walking, tools:Tooling, RoboCup 2025 ⚽

#1945 Draw segments with dynamic width
  Cargo.lock
  tools/pepsi/Cargo.toml
  tools/twix/src/panels/image_segments.rs
Labels: RoboCup 2025 ⚽

#1960 robustify foot switches
  crates/walking_engine/src/parameters.rs
  crates/walking_engine/src/step_state.rs
  etc/parameters/default.json
Labels: cat:Walking, RoboCup 2025 ⚽

#1970 Fix loca set transition
  crates/control/src/localization.rs
Labels: cat:Localization, is:Bugfix, RoboCup 2025 ⚽

#1973 Allow specifying Frame in point! and vector! macros
  crates/linear_algebra/src/point.rs
  crates/linear_algebra/src/vector.rs
Labels: RoboCup 2025 ⚽

#1965 Improve Camera Calibration
  crates/bevyhavior_simulator/src/robot.rs
  crates/control/src/camera_matrix_calculator.rs
  crates/control/src/game_controller_state_filter.rs
  crates/control/src/localization.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
  etc/parameters/head.P0000074A03S84400010.json
  etc/parameters/head.P0000074A03S85B00016.json
  etc/parameters/head.P0000074A04S8CP00037.json
  etc/parameters/head.P0000074A04S8CP00040.json
  etc/parameters/head.P0000074A04S8CP00042.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A05S99M00009.json
  etc/parameters/head.P0000074A06S9A900006.json
  etc/parameters/head.P0000074A06S9A900031.json
  etc/parameters/head.P0000074A09S28J00025.json
  etc/parameters/head.P0000074A09S31C00023.json
  etc/parameters/head.P0000074A09S31C00028.json
  etc/parameters/head.P0000074A09S31C00029.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
  tools/twix/src/panels/automatic_camera_calibration_export.rs
  tools/twix/src/panels/camera_calibration/optimization.rs
  tools/twix/src/panels/camera_calibration/panel.rs
  tools/twix/src/panels/image/overlays/field_lines.rs
  tools/twix/src/panels/manual_camera_calibration.rs
Labels: tools:Debug Tooling, calibration:Manual, RoboCup 2025 ⚽

#1974 Stand up ouch fix and made it louder
  crates/control/src/behavior/stand_up.rs
  crates/types/src/motion_selection.rs
  etc/sounds/Ouch.ogg
Labels: cat:Motion, RoboCup 2025 ⚽

#1953 Load multiple datasets for field color training
  crates/vision/src/field_color_tree.rs
  tools/field_color_detection/.gitattributes
  tools/field_color_detection/DT_tuned.joblib
  tools/field_color_detection/run_optimization_pipeline.py
  tools/field_color_detection/src/field_color_detection/data.py
  tools/field_color_detection/src/field_color_detection/objective.py
  tools/field_color_detection/src/field_color_detection/settings.py
  tools/field_color_detection/train_decision_tree.py
  tools/field_color_detection/tree_to_rust.py
Labels: RoboCup 2025 ⚽

#1978 Tune walking and catching
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#1988 Add noise scaling, to reduce influence of little gyro
  crates/walking_engine/src/foot_leveling.rs
  crates/walking_engine/src/gyro_balancing.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: RoboCup 2025 ⚽

#1990 Calibrate Wistex testgame
  etc/parameters/head.P0000074A09S31C00023.json
  etc/parameters/head.P0000074A09S31C00037.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00047.json
  etc/parameters/head.P0000074A10S41M00048.json
Labels: cat:Calibration, calibration:Manual, RoboCup 2025 ⚽

#1976 Remove unused maximum_step_size
  crates/control/src/behavior/intercept_ball.rs
  crates/control/src/behavior/node.rs
Labels: is:Cleanup

#1972 Use parry2d convex hull computation
  Cargo.lock
  Cargo.toml
  crates/control/src/zero_moment_point_provider.rs
  crates/geometry/Cargo.toml
  crates/geometry/src/convex_hull.rs
  crates/geometry/src/polygon.rs
  crates/linear_algebra/src/framed.rs
  crates/vision/src/limb_projector.rs
Labels: RoboCup 2025 ⚽

#1999 Fix pepsi path autocompletions for fish
  Cargo.lock
  tools/pepsi/Cargo.toml
  tools/pepsi/src/completions.rs
Labels: RoboCup 2025 ⚽

#2006 Everyone should look for referee in Standby
  crates/control/src/behavior/initial.rs
Labels: cat:Vision, RoboCup 2025 ⚽

#2010 Tune ground provider
  crates/control/src/ground_provider.rs
  crates/walking_engine/src/mode/catching.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
  etc/parameters/head.P0000074A09S31C00029.json
Labels: cat:Walking, RoboCup 2025 ⚽

#2018 Tune feet-detection parameter for RC25
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2011 Discard spurious obstacles
  crates/control/src/obstacle_filter.rs
  crates/types/src/obstacles.rs
Labels: cat:Filtering, is:Bugfix, RoboCup 2025 ⚽

#2020 Trust lines a little more
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2021 Do not check edge gradient for line detection on top
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2016 Parameter based Standby visual referee robot selection
  crates/control/src/behavior/initial.rs
  crates/control/src/behavior/node.rs
Labels: cat:Behavior, RoboCup 2025 ⚽

#2017 Do not produce segments with zero length
  crates/vision/src/image_segmenter.rs
Labels: RoboCup 2025 ⚽

#2019 Add parameter to ignore team balls for striker claiming
  crates/control/src/role_assignment.rs
  etc/parameters/default.json
Labels: cat:Behavior, RoboCup 2025 ⚽

#2026 Clip goal-line targets with ball position
  crates/control/src/kick_selector.rs
Labels: RoboCup 2025 ⚽

#2033 Add localization overlay
  tools/twix/src/panels/map/layers/localization.rs
  tools/twix/src/panels/map/layers/mod.rs
  tools/twix/src/panels/map/mod.rs
Labels: tools:Tooling, RoboCup 2025 ⚽

#2032 Prevent non-strikers from claiming striker at kickoff
  crates/bevyhavior_simulator/src/bin/kicking_team_filtering.rs
  crates/bevyhavior_simulator/src/test_rules.rs
  crates/control/src/role_assignment.rs
  crates/control/src/team_ball_receiver.rs
Labels: cat:Behavior, cat:Filtering, RoboCup 2025 ⚽

#2037 Tune walking
  crates/control/src/ground_provider.rs
  crates/walking_engine/src/mode/catching.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2040 Calibrations 2025-07-18 Wistex
  etc/parameters/head.P0000074A03S84400010.json
  etc/parameters/head.P0000074A05S98U00019.json
  etc/parameters/head.P0000074A09S31C00023.json
  etc/parameters/head.P0000074A09S31C00029.json
  etc/parameters/head.P0000074A09S31T00003.json
  etc/parameters/head.P0000074A10S41M00040.json
  etc/parameters/head.P0000074A10S41M00047.json
Labels: cat:Calibration, calibration:Manual, RoboCup 2025 ⚽

#2039 tune foot leveling
  etc/parameters/default.json
Labels: cat:Walking, ParameterChangesOnly, RoboCup 2025 ⚽

#2043 do not balance when catching
  crates/walking_engine/src/mode/catching.rs
  crates/walking_engine/src/parameters.rs
  etc/parameters/default.json
Labels: RoboCup 2025 ⚽

#2053 Update odometry
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2055 tune walking, fix 37
  etc/parameters/body.P0000073A19S31T00003.json
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2041 Add `Path` newtype
  crates/bevyhavior_simulator/src/autoref.rs
  crates/bevyhavior_simulator/src/test_rules.rs
  crates/control/src/behavior/intercept_ball.rs
  crates/control/src/behavior/search.rs
  crates/control/src/behavior/walk_to_pose.rs
  crates/control/src/dribble_path_planner.rs
  crates/control/src/motion/step_planner.rs
  crates/control/src/path_planner.rs
  crates/control/src/time_to_reach_kick_position.rs
  crates/types/src/dribble_path_plan.rs
  crates/types/src/motion_command.rs
  crates/types/src/planned_path.rs
  tools/twix/src/twix_painter.rs
Labels: is:Easy, is:Refactoring

#2058 Slower turning when searching
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2062 Remove unused features from `parry2d` crate
  Cargo.lock
  Cargo.toml
Labels: is:Cleanup, is:Easy, mit Qualitätsgarantie, RoboCup 2025 ⚽

#2063 Look at referee during `Initial` without pose detection
  crates/control/src/behavior/initial.rs
  crates/control/src/behavior/node.rs
Labels: cat:Vision, RoboCup 2025 ⚽

#2059 Longer ttrkp when fallen
  crates/control/src/motion/motion_selector.rs
  crates/control/src/motion/stand_up_front.rs
  crates/control/src/motion/stand_up_sitting.rs
  crates/control/src/time_to_reach_kick_position.rs
  crates/types/src/parameters.rs
  etc/motions/stand_up_back.json
  etc/parameters/default.json
Labels: RoboCup 2025 ⚽

#2072 Update odometry
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2074 Increase walk-and-stand hysteresis for supporter
  crates/control/src/behavior/support.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: RoboCup 2025 ⚽

#2060 Reduce max head yaw velocity
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2073 Don't continuously turn when searching
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/search.rs
  crates/types/src/parameters.rs
  etc/parameters/default.json
Labels: cat:Behavior, RoboCup 2025 ⚽

#2077 Tune Kicks
  crates/bevyhavior_simulator/src/bin/intercept_ball.rs
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2038 remove_anchor_from_robot
  crates/bevyhavior_simulator/src/robot.rs
Labels: is:Bugfix

#2044 Don't trust network teamballs
  crates/bevyhavior_simulator/src/bin/striker_from_unseen_ball.rs
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#2083 Incease `ball_radius_enlargement_factor` of `Top` to 1.8
  etc/parameters/default.json
Labels: ParameterChangesOnly, RoboCup 2025 ⚽

#1735 Searcher Standing Delay
  crates/bevyhavior_simulator/src/bin/passive_defender_positioning.rs
  crates/bevyhavior_simulator/src/bin/standing_searcher.rs
  crates/control/src/behavior/node.rs
  crates/control/src/behavior/search.rs
  crates/control/src/world_state_composer.rs
  crates/types/src/parameters.rs
  crates/types/src/world_state.rs
  etc/parameters/default.json
Labels: cat:Behavior, RoboCup 2025 ⚽

#2092 Remove unused VisualRefereeChallenge
  crates/spl_network_messages/build.rs
  crates/spl_network_messages/headers/VisualRefereeChallenge.hpp
Labels: is:Cleanup

#2076 Change from loser to searcher after a timeout
  crates/control/src/role_assignment.rs
  etc/parameters/default.json
Labels: cat:Behavior
